/* Auto-generated by Guing — do not edit manually */
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      // Enforce single-DS-import invariant:
      // All UI library primitives MUST be imported via the adapter's internal entrypoint,
      // never from the raw package. This ensures the DS package remains the single source
      // of truth and developers can't accidentally bypass generated token bindings.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@mui/material", "@mui/material/*"],
              message: "Import from '../adapters/mui/internal' instead of '@mui/material' directly.",
            },
          ],
        },
      ],
      // Generated components always emit the full standard prop interface (onClick,
      // onHover, isLoading, sx, …) even when a given component doesn't use every prop,
      // and token/theme helpers legitimately use `any`. These are expected in
      // auto-generated code — the enforced invariant here is no-restricted-imports.
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    // Adapter internal files themselves must be allowed to import from raw packages
    // and may use @ts-nocheck / @ts-ignore for tricky library default-export types.
    files: ["src/components/adapters/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": "off",
      "@typescript-eslint/ban-ts-comment": "off",
    },
  },
  {
    // Protected token-driven Typography bridge — library-agnostic, uses @ts-nocheck
    // for the dynamic token→component generation. Keeps no-restricted-imports on.
    files: ["src/components/Text/Text.tsx"],
    rules: {
      "@typescript-eslint/ban-ts-comment": "off",
    },
  },
];
