/* Auto-generated by Guing — do not edit manually */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
    "0e92cb": "var(--color-0e92cb)",
    "button": "var(--color-button)",
    "button": "var(--color-button)",
    "error": "var(--color-error)",
    "helper-text": "var(--color-helper-text)",
    "input-dropdown": "var(--color-input-dropdown)",
    "input-dropdown-txt": "var(--color-input-dropdown-txt)",
    "new-buttons": "var(--color-new-buttons)",
      },
      fontFamily: {
    "inter": ["Inter", "sans-serif"],
      },
    },
  },
};
