/* Auto-generated by Guing — do not edit manually */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
    "d7e3ec": "var(--color-d7e3ec)",
    "button": "var(--color-button)",
    "button": "var(--color-button)",
    "buttons": "var(--color-buttons)",
    "buttons": "var(--color-buttons)",
    "buttons": "var(--color-buttons)",
    "error": "var(--color-error)",
    "helper-text": "var(--color-helper-text)",
    "input-dropdown": "var(--color-input-dropdown)",
    "input-dropdown-txt": "var(--color-input-dropdown-txt)",
      },
      fontFamily: {
    "inter": ["Inter", "sans-serif"],
      },
    },
  },
};
