/* Auto-generated by Guing — do not edit manually */

import { PrimaryButton } from '../PrimaryButton/PrimaryButton';

export const PrimaryButton = {
  PrimaryButton: PrimaryButton,
};

export { PrimaryButton };
