/* Auto-generated by Guing — do not edit manually */

import { ButtonOutline } from '../ButtonOutline/ButtonOutline';
import { ButtonSecondary } from '../ButtonSecondary/ButtonSecondary';
import { ButtonPrimary } from '../ButtonPrimary/ButtonPrimary';

export const Button = {
  Outline: ButtonOutline,
  Secondary: ButtonSecondary,
  Primary: ButtonPrimary,
};

export { ButtonOutline, ButtonSecondary, ButtonPrimary };
