/* Auto-generated by Guing — do not edit manually */

import { ButtonSecondary } from '../ButtonSecondary/ButtonSecondary';

export const Button = {
  Secondary: ButtonSecondary,
};

export { ButtonSecondary };
