/* Auto-generated by Guing — do not edit manually */

import { ButtonPrimary } from '../ButtonPrimary/ButtonPrimary';
import { ButtonOutline } from '../ButtonOutline/ButtonOutline';
import { ButtonSecondary } from '../ButtonSecondary/ButtonSecondary';

export const Button = {
  Primary: ButtonPrimary,
  Outline: ButtonOutline,
  Secondary: ButtonSecondary,
};

export { ButtonPrimary, ButtonOutline, ButtonSecondary };
