/* Auto-generated by Guing — do not edit manually */
import tokens from './tokens.json';
import type { DesignTokens } from './types';

export const designTokens: DesignTokens = tokens as any;
export * from './types';
