/* Auto-generated by Guing — do not edit manually */

export * from './types';

export const tokens = {
  "colors": [
    {
      "name": "surface/elavate/L1",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/elavate/L2",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/white/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/black/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/bold_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/subtle_400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/bold_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/neutral/bold_400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/primary/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/primary/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/primary/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/primary/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/primary/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/primary/bold_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/danger/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/danger/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/white/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/white/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/neutral/subtle_500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/neutral/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/neutral/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/neutral/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/neutral/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/primary/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/primary/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/primary/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/primary/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/primary/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/danger/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/danger/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/info/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/info/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/success/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/success/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/warning/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "text/warning/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/neutral/subtle_500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/danger/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/neutral/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/neutral/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/danger/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/neutral/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/neutral/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/info/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/info/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/info/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/white/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/subtle_400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/info/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/primary/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/primary/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/primary/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/primary/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/success/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/success/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/success/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/success/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/primary/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/primary/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/primary/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/primary/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/primary/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/warning/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/warning/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/warning/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/warning/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/state-interaction/hover/neutral",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/state-interaction/hover/primary",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/state-interaction/hover/danger",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/state-interaction/hover/white",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/state-interaction/selected/neutral",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/state-interaction/disabled/neutral",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/overlay/light/60",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/overlay/light/75",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/white/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/white/alpha-30",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/white/alpha-60",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/white/alpha-75",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/black/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/black/alpha-30",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/black/alpha-60",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/black/alpha-75",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/50",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/600",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/800",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/neutral/900",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/50",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/250",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/50",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/600",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/primary/700",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/50",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/600",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/danger/700",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/600",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/info/700",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/50",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/600",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/success/700",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/50",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/600",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "fixed/warning/700",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "misc/status/offline",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "misc/status/online",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/danger/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/danger/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/danger/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/danger/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/info/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/info/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/danger/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/info/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/info/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/info/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/success/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/success/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/success/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/success/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/warning/subtle_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/warning/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/success/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/warning/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/warning/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/warning/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/danger/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/danger/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/info/subtle_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/danger/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/info/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/info/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/info/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/success/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/success/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/success/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/warning/subtle_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/warning/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "icon/warning/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/bold_300",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "border/neutral/bold_400",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/overlay/dark/60",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "background/overlay/dark/75",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/onSurface/base",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/onSurface/bold_100",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "surface/onSurface/bold_200",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "color/white/base-#FFFFFF",
      "value": "#FFFFFF",
      "category": "Variables"
    },
    {
      "name": "color/white/alpha-30-#FFFFFF(30%)",
      "value": "#FFFFFF",
      "category": "Variables"
    },
    {
      "name": "color/white/alpha-60-#FFFFFF(60%)",
      "value": "#FFFFFF",
      "category": "Variables"
    },
    {
      "name": "color/white/alpha-75-#FFFFFF(75%)",
      "value": "#FFFFFF",
      "category": "Variables"
    },
    {
      "name": "color/black/base-#121212",
      "value": "#101114",
      "category": "Variables"
    },
    {
      "name": "color/black/alpha-30-#121212(30%)",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "color/black/alpha-60-#121212(60%)",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "color/black/alpha-75-#121212(75%)",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "color/neutral/50-#FCFCFD",
      "value": "#FCFCFD",
      "category": "Variables"
    },
    {
      "name": "color/neutral/100-#F2F4F7",
      "value": "#F2F4F7",
      "category": "Variables"
    },
    {
      "name": "color/neutral/200-#E4E7EC",
      "value": "#E4E7EC",
      "category": "Variables"
    },
    {
      "name": "color/neutral/300-#D0D5DD",
      "value": "#D0D5DD",
      "category": "Variables"
    },
    {
      "name": "color/neutral/400-#ABB1BA",
      "value": "#8B939F",
      "category": "Variables"
    },
    {
      "name": "color/neutral/500-#7A7F89",
      "value": "#6E7581",
      "category": "Variables"
    },
    {
      "name": "color/neutral/600-#40444D",
      "value": "#40444D",
      "category": "Variables"
    },
    {
      "name": "color/neutral/700-#282B31",
      "value": "#282B31",
      "category": "Variables"
    },
    {
      "name": "color/neutral/800-#1D1F23",
      "value": "#1D1F23",
      "category": "Variables"
    },
    {
      "name": "color/neutral/900-#17181C",
      "value": "#17181A",
      "category": "Variables"
    },
    {
      "name": "color/primary/50-#ECF4FC",
      "value": "#ECF4FC",
      "category": "Variables"
    },
    {
      "name": "color/primary/100-#D8E9F9",
      "value": "#D8E9F9",
      "category": "Variables"
    },
    {
      "name": "color/primary/200-#86C3F9",
      "value": "#86C3F9",
      "category": "Variables"
    },
    {
      "name": "color/primary/250-#65ABF1",
      "value": "#65ABF1",
      "category": "Variables"
    },
    {
      "name": "color/primary/300-#4B96E7",
      "value": "#4B96E7",
      "category": "Variables"
    },
    {
      "name": "color/primary/400-#0354A6",
      "value": "#0354A6",
      "category": "Variables"
    },
    {
      "name": "color/primary/500-#064280",
      "value": "#064280",
      "category": "Variables"
    },
    {
      "name": "color/primary/600-#012242",
      "value": "#012242",
      "category": "Variables"
    },
    {
      "name": "color/primary/700-#011121",
      "value": "#011121",
      "category": "Variables"
    },
    {
      "name": "color/danger/50-#FEF3F2",
      "value": "#FEF3F2",
      "category": "Variables"
    },
    {
      "name": "color/danger/100-#FDE1E1",
      "value": "#FDE1E1",
      "category": "Variables"
    },
    {
      "name": "color/danger/200-#FCA5A5",
      "value": "#FCA5A5",
      "category": "Variables"
    },
    {
      "name": "color/danger/300-#ED7D75",
      "value": "#ED7D75",
      "category": "Variables"
    },
    {
      "name": "color/danger/400-#BB251A",
      "value": "#BB251A",
      "category": "Variables"
    },
    {
      "name": "color/danger/500-#831A12",
      "value": "#831A12",
      "category": "Variables"
    },
    {
      "name": "color/danger/600-#4B0F0A",
      "value": "#4B0F0A",
      "category": "Variables"
    },
    {
      "name": "color/danger/700-#250705",
      "value": "#250705",
      "category": "Variables"
    },
    {
      "name": "color/info/50-#F1F7FD",
      "value": "#EEF8FB",
      "category": "Variables"
    },
    {
      "name": "color/info/100-#DCEDFC",
      "value": "#DAF0F6",
      "category": "Variables"
    },
    {
      "name": "color/info/200-#84CAFF",
      "value": "#7DD1E8",
      "category": "Variables"
    },
    {
      "name": "color/info/300-#53A1EB",
      "value": "#2E9AB8",
      "category": "Variables"
    },
    {
      "name": "color/info/400-#1465B4",
      "value": "#0E7B9B",
      "category": "Variables"
    },
    {
      "name": "color/info/500-#0C3D6C",
      "value": "#0A5A70",
      "category": "Variables"
    },
    {
      "name": "color/info/600-#0A335A",
      "value": "#093F4E",
      "category": "Variables"
    },
    {
      "name": "color/info/700-#061E36",
      "value": "#05252E",
      "category": "Variables"
    },
    {
      "name": "color/success/50-#EFFFF8",
      "value": "#EFFFF8",
      "category": "Variables"
    },
    {
      "name": "color/success/100-#D6F3E9",
      "value": "#D8F3E7",
      "category": "Variables"
    },
    {
      "name": "color/success/200-#79D7AC",
      "value": "#79D7AC",
      "category": "Variables"
    },
    {
      "name": "color/success/300-#35AD77",
      "value": "#35AD77",
      "category": "Variables"
    },
    {
      "name": "color/success/400-#039855",
      "value": "#03834A",
      "category": "Variables"
    },
    {
      "name": "color/success/500-#045130",
      "value": "#045130",
      "category": "Variables"
    },
    {
      "name": "color/success/600-#012E19",
      "value": "#012E19",
      "category": "Variables"
    },
    {
      "name": "color/success/700-#011E11",
      "value": "#011E11",
      "category": "Variables"
    },
    {
      "name": "color/warning/50-#FFF9F4",
      "value": "#FFF9F4",
      "category": "Variables"
    },
    {
      "name": "color/warning/100-#FCF0DB",
      "value": "#FCECD9",
      "category": "Variables"
    },
    {
      "name": "color/warning/200-#FFC78F",
      "value": "#FFC78F",
      "category": "Variables"
    },
    {
      "name": "color/warning/300-#E7954F",
      "value": "#E7954F",
      "category": "Variables"
    },
    {
      "name": "color/warning/400-#DC6803",
      "value": "#B45803",
      "category": "Variables"
    },
    {
      "name": "color/warning/500-#7F3004",
      "value": "#7E3E07",
      "category": "Variables"
    },
    {
      "name": "color/warning/600-#421F01",
      "value": "#421F01",
      "category": "Variables"
    },
    {
      "name": "color/warning/700-#2C1501",
      "value": "#2C1501",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/primary-light",
      "value": "#0354A6",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/primary-dark",
      "value": "#5EAEFF",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/gray-light",
      "value": "#1D1F23",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/gray-dark",
      "value": "#FCFCFD",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/white-light",
      "value": "#FFFFFF",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/white-dark",
      "value": "#FFFFFF",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/danger-light",
      "value": "#BB251A",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/hover/danger-dark",
      "value": "#ED7D75",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/selected/gray-light",
      "value": "#17181C",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/selected/gray-dark",
      "value": "#FCFCFD",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/disabled/gray-light",
      "value": "#17181C",
      "category": "Variables"
    },
    {
      "name": "color/misc/state/disabled/gray-dark",
      "value": "#FCFCFD",
      "category": "Variables"
    },
    {
      "name": "color/onSurface",
      "value": "#F2F4F7",
      "category": "Variables"
    },
    {
      "name": "Misc/Hover bg/Neutral",
      "value": "#101828",
      "category": "Styles"
    },
    {
      "name": "Brand 500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Action Primary",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Success 500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Warning 500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Danger 500",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Background",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Surface",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Text Main",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Text Muted",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Border Divider",
      "value": "#000000",
      "category": "Variables"
    },
    {
      "name": "Brand 100",
      "value": "#D9D9D9",
      "category": "Semantic"
    },
    {
      "name": "Brand 300",
      "value": "#666666",
      "category": "Semantic"
    },
    {
      "name": "Brand 700",
      "value": "#000000",
      "category": "Semantic"
    },
    {
      "name": "White",
      "value": "#FFFFFF",
      "category": "Semantic"
    },
    {
      "name": "Black",
      "value": "#000000",
      "category": "Semantic"
    },
    {
      "name": "Neutral 300",
      "value": "#D1D5DB",
      "category": "Semantic"
    },
    {
      "name": "Action Secondary",
      "value": "#6b7280",
      "category": "Semantic"
    }
  ],
  "typography": [
    {
      "name": "H1/Regular",
      "fontFamily": "Nunito Sans",
      "fontSize": 36,
      "fontWeight": 400,
      "lineHeight": 44
    },
    {
      "name": "H1/Bold",
      "fontFamily": "Nunito Sans",
      "fontSize": 36,
      "fontWeight": 700,
      "lineHeight": 44
    },
    {
      "name": "H2/Regular",
      "fontFamily": "Nunito Sans",
      "fontSize": 32,
      "fontWeight": 400,
      "lineHeight": 40
    },
    {
      "name": "H2/Bold",
      "fontFamily": "Nunito Sans",
      "fontSize": 32,
      "fontWeight": 700,
      "lineHeight": 40
    },
    {
      "name": "H3/Regular",
      "fontFamily": "Nunito Sans",
      "fontSize": 28,
      "fontWeight": 400,
      "lineHeight": 36
    },
    {
      "name": "H3/Bold",
      "fontFamily": "Nunito Sans",
      "fontSize": 28,
      "fontWeight": 700,
      "lineHeight": 36
    },
    {
      "name": "H4/Regular",
      "fontFamily": "Nunito Sans",
      "fontSize": 24,
      "fontWeight": 400,
      "lineHeight": 32
    },
    {
      "name": "H4/Bold",
      "fontFamily": "Nunito Sans",
      "fontSize": 24,
      "fontWeight": 700,
      "lineHeight": 32
    },
    {
      "name": "H5/Regular",
      "fontFamily": "Nunito Sans",
      "fontSize": 20,
      "fontWeight": 400,
      "lineHeight": 28
    },
    {
      "name": "H5/Bold",
      "fontFamily": "Nunito Sans",
      "fontSize": 20,
      "fontWeight": 700,
      "lineHeight": 28
    },
    {
      "name": "Text-lg/Regular",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 400,
      "lineHeight": 28
    },
    {
      "name": "Text-lg/Medium",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 500,
      "lineHeight": 28
    },
    {
      "name": "Text-lg/Semibold",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 600,
      "lineHeight": 28
    },
    {
      "name": "Text-lg/Regular - Underline",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 400,
      "lineHeight": 28
    },
    {
      "name": "Text-lg/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 500,
      "lineHeight": 28
    },
    {
      "name": "Text-md (l-24)/Regular",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": 24
    },
    {
      "name": "Text-md (l-24)/Medium",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 500,
      "lineHeight": 24
    },
    {
      "name": "Text-md (l-24)/Semibold",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 600,
      "lineHeight": 24
    },
    {
      "name": "Text-md (l-24)/Regular- Underline",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": 24
    },
    {
      "name": "Text-md (l-24)/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 500,
      "lineHeight": 24
    },
    {
      "name": "Text-md (l-20)/Regular",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": 20
    },
    {
      "name": "Text-md (l-20)/Medium",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 500,
      "lineHeight": 20
    },
    {
      "name": "Text-md (l-20)/Semibold",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 600,
      "lineHeight": 20
    },
    {
      "name": "Text-md (l-20)/Regular - Underline",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": 20
    },
    {
      "name": "Text-md (l-20)/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 500,
      "lineHeight": 20
    },
    {
      "name": "Text-sm (l-20)/Regular",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 20
    },
    {
      "name": "Text-sm (l-20)/Medium",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": 20
    },
    {
      "name": "Text-sm (l-20)/Semibold",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 600,
      "lineHeight": 20
    },
    {
      "name": "Text-sm (l-20)/Regular - Underline",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 20
    },
    {
      "name": "Text-sm (l-20)/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": 20
    },
    {
      "name": "Text-sm (l-16)/Regular",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 16
    },
    {
      "name": "Text-sm (l-16)/Medium",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": 16
    },
    {
      "name": "Text-sm (l-16)/Semibold",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 600,
      "lineHeight": 16
    },
    {
      "name": "Text-sm (l-16)/Regular - Underline",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 16
    },
    {
      "name": "Text-sm (l-16)/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": 16
    },
    {
      "name": "Text-xs/Regular",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 400,
      "lineHeight": 18
    },
    {
      "name": "Text-xs/Medium",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 500,
      "lineHeight": 18
    },
    {
      "name": "Text-xs/Semibold",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 600,
      "lineHeight": 18
    },
    {
      "name": "Text-xs/Regular - Underline",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 400,
      "lineHeight": 18
    },
    {
      "name": "Text-xs/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 500,
      "lineHeight": 18
    },
    {
      "name": "Text-xxs/Regular",
      "fontFamily": "Inter",
      "fontSize": 10,
      "fontWeight": 400,
      "lineHeight": 14
    },
    {
      "name": "Text-xxs/Medium",
      "fontFamily": "Inter",
      "fontSize": 10,
      "fontWeight": 500,
      "lineHeight": 14
    },
    {
      "name": "Text-xxs/Semibold",
      "fontFamily": "Inter",
      "fontSize": 10,
      "fontWeight": 600,
      "lineHeight": 14
    },
    {
      "name": "Text-xxs/Regular - Underline",
      "fontFamily": "Inter",
      "fontSize": 10,
      "fontWeight": 400,
      "lineHeight": 14
    },
    {
      "name": "Text-xxs/Medium - Underline",
      "fontFamily": "Inter",
      "fontSize": 10,
      "fontWeight": 500,
      "lineHeight": 14
    },
    {
      "name": "Heading 1",
      "fontFamily": "Nunito Sans",
      "fontSize": 36,
      "fontWeight": 400,
      "lineHeight": 44
    },
    {
      "name": "Heading 2",
      "fontFamily": "Nunito Sans",
      "fontSize": 32,
      "fontWeight": 400,
      "lineHeight": 40
    },
    {
      "name": "Heading 3",
      "fontFamily": "Nunito Sans",
      "fontSize": 28,
      "fontWeight": 400,
      "lineHeight": 36
    },
    {
      "name": "Body Large",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 400,
      "lineHeight": 28
    },
    {
      "name": "Body Regular",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": 24
    },
    {
      "name": "Body Small",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 20
    },
    {
      "name": "Caption",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 400,
      "lineHeight": 18
    }
  ],
  "radius": [
    {
      "name": "border-radius/none",
      "value": 0,
      "topLeft": 0,
      "topRight": 0,
      "bottomRight": 0,
      "bottomLeft": 0,
      "category": "shape"
    },
    {
      "name": "border-radius/xs",
      "value": 4,
      "topLeft": 4,
      "topRight": 4,
      "bottomRight": 4,
      "bottomLeft": 4,
      "category": "shape"
    },
    {
      "name": "border-radius/sm",
      "value": 6,
      "topLeft": 6,
      "topRight": 6,
      "bottomRight": 6,
      "bottomLeft": 6,
      "category": "shape"
    },
    {
      "name": "border-radius/md",
      "value": 8,
      "topLeft": 8,
      "topRight": 8,
      "bottomRight": 8,
      "bottomLeft": 8,
      "category": "shape"
    },
    {
      "name": "border-radius/lg",
      "value": 12,
      "topLeft": 12,
      "topRight": 12,
      "bottomRight": 12,
      "bottomLeft": 12,
      "category": "shape"
    },
    {
      "name": "border-radius/xl",
      "value": 16,
      "topLeft": 16,
      "topRight": 16,
      "bottomRight": 16,
      "bottomLeft": 16,
      "category": "shape"
    },
    {
      "name": "border-radius/2xl",
      "value": 24,
      "topLeft": 24,
      "topRight": 24,
      "bottomRight": 24,
      "bottomLeft": 24,
      "category": "shape"
    },
    {
      "name": "border-radius/3xl",
      "value": 32,
      "topLeft": 32,
      "topRight": 32,
      "bottomRight": 32,
      "bottomLeft": 32,
      "category": "shape"
    },
    {
      "name": "border-radius/full",
      "value": 9999,
      "topLeft": 9999,
      "topRight": 9999,
      "bottomRight": 9999,
      "bottomLeft": 9999,
      "category": "shape"
    },
    {
      "name": "Small",
      "value": 6,
      "topLeft": 6,
      "topRight": 6,
      "bottomRight": 6,
      "bottomLeft": 6,
      "category": "shape"
    },
    {
      "name": "Medium",
      "value": 8,
      "topLeft": 8,
      "topRight": 8,
      "bottomRight": 8,
      "bottomLeft": 8,
      "category": "shape"
    },
    {
      "name": "Large",
      "value": 12,
      "topLeft": 12,
      "topRight": 12,
      "bottomRight": 12,
      "bottomLeft": 12,
      "category": "shape"
    },
    {
      "name": "Round",
      "value": 9999,
      "topLeft": 9999,
      "topRight": 9999,
      "bottomRight": 9999,
      "bottomLeft": 9999,
      "category": "shape"
    }
  ],
  "gaps": [
    {
      "name": "heading/H2/letter-spacing",
      "value": -0.019999999552965164,
      "category": "typography"
    },
    {
      "name": "heading/H2/paragaph-spacing",
      "value": 28,
      "category": "typography"
    },
    {
      "name": "heading/H1/letter-spacing",
      "value": -0.019999999552965164,
      "category": "typography"
    },
    {
      "name": "heading/H1/paragaph-spacing",
      "value": 32,
      "category": "typography"
    },
    {
      "name": "heading/H4/letter-spacing",
      "value": 0,
      "category": "typography"
    },
    {
      "name": "heading/H4/paragaph-spacing",
      "value": 20,
      "category": "typography"
    },
    {
      "name": "heading/H3/letter-spacing",
      "value": -0.019999999552965164,
      "category": "typography"
    },
    {
      "name": "heading/H3/paragaph-spacing",
      "value": 24,
      "category": "typography"
    },
    {
      "name": "body/lg/letter-spacing",
      "value": 0,
      "category": "typography"
    },
    {
      "name": "body/lg/paragaph-spacing",
      "value": 24,
      "category": "typography"
    },
    {
      "name": "body/sm/letter-spacing",
      "value": 0,
      "category": "typography"
    },
    {
      "name": "body/sm/paragaph-spacing",
      "value": 16,
      "category": "typography"
    },
    {
      "name": "body/md/letter-spacing",
      "value": 0,
      "category": "typography"
    },
    {
      "name": "body/md/paragaph-spacing",
      "value": 20,
      "category": "typography"
    },
    {
      "name": "body/xs/letter-spacing",
      "value": 0.009999999776482582,
      "category": "typography"
    },
    {
      "name": "body/xs/paragaph-spacing",
      "value": 12,
      "category": "typography"
    },
    {
      "name": "heading/H5/letter-spacing",
      "value": 0,
      "category": "typography"
    },
    {
      "name": "heading/H5/paragaph-spacing",
      "value": 16,
      "category": "typography"
    },
    {
      "name": "body/xxs/letter-spacing",
      "value": 0.019999999552965164,
      "category": "typography"
    },
    {
      "name": "body/xxs/paragaph-spacing",
      "value": 8,
      "category": "typography"
    }
  ],
  "sizes": [
    {
      "name": "font-weight/Regular - 400",
      "value": 400,
      "category": "_global"
    },
    {
      "name": "dimension/null",
      "value": 0,
      "category": "_global"
    },
    {
      "name": "dimension/4 - 0_25 rem",
      "value": 4,
      "category": "_global"
    },
    {
      "name": "dimension/6 - 0_375 rem",
      "value": 6,
      "category": "_global"
    },
    {
      "name": "dimension/8 - 0_5 rem",
      "value": 8,
      "category": "_global"
    },
    {
      "name": "dimension/10 - 0_625 rem",
      "value": 10,
      "category": "_global"
    },
    {
      "name": "dimension/12 - 0_75 rem",
      "value": 12,
      "category": "_global"
    },
    {
      "name": "dimension/14 - 0_875 rem",
      "value": 14,
      "category": "_global"
    },
    {
      "name": "dimension/16 - 1 rem",
      "value": 16,
      "category": "_global"
    },
    {
      "name": "dimension/18 - 1_125 rem",
      "value": 18,
      "category": "_global"
    },
    {
      "name": "dimension/20 - 1_25 rem",
      "value": 20,
      "category": "_global"
    },
    {
      "name": "dimension/24 - 1_5 rem",
      "value": 24,
      "category": "_global"
    },
    {
      "name": "dimension/28 - 1_75 rem",
      "value": 28,
      "category": "_global"
    },
    {
      "name": "dimension/32 - 2 rem",
      "value": 32,
      "category": "_global"
    },
    {
      "name": "dimension/36 - 2_25 rem",
      "value": 36,
      "category": "_global"
    },
    {
      "name": "dimension/40 - 2_5 rem",
      "value": 40,
      "category": "_global"
    },
    {
      "name": "dimension/44 - 2_75 rem",
      "value": 44,
      "category": "_global"
    },
    {
      "name": "dimension/56 - 3_5 rem",
      "value": 56,
      "category": "_global"
    },
    {
      "name": "dimension/64 - 4 rem",
      "value": 64,
      "category": "_global"
    },
    {
      "name": "dimension/80 - 5 rem",
      "value": 80,
      "category": "_global"
    },
    {
      "name": "dimension/96 - 6 rem",
      "value": 96,
      "category": "_global"
    },
    {
      "name": "dimension/full",
      "value": 999,
      "category": "_global"
    },
    {
      "name": "font-weight/Medium - 500",
      "value": 500,
      "category": "_global"
    },
    {
      "name": "font-weight/Semibold - 600",
      "value": 600,
      "category": "_global"
    },
    {
      "name": "font-weight/Bold - 700",
      "value": 700,
      "category": "_global"
    },
    {
      "name": "font-weight/Extrabold - 800",
      "value": 800,
      "category": "_global"
    },
    {
      "name": "border-width/none",
      "value": 0,
      "category": "shape"
    },
    {
      "name": "border-width/thin",
      "value": 1,
      "category": "shape"
    },
    {
      "name": "border-width/medium",
      "value": 2,
      "category": "shape"
    },
    {
      "name": "border-width/thick",
      "value": 4,
      "category": "shape"
    },
    {
      "name": "heading/H1/font-size",
      "value": 36,
      "category": "typography"
    },
    {
      "name": "heading/H2/font-size",
      "value": 32,
      "category": "typography"
    },
    {
      "name": "heading/H2/line-height",
      "value": 40,
      "category": "typography"
    },
    {
      "name": "heading/H1/line-height",
      "value": 44,
      "category": "typography"
    },
    {
      "name": "heading/H3/font-size",
      "value": 28,
      "category": "typography"
    },
    {
      "name": "heading/H4/font-size",
      "value": 24,
      "category": "typography"
    },
    {
      "name": "heading/H4/line-height",
      "value": 32,
      "category": "typography"
    },
    {
      "name": "heading/H3/line-height",
      "value": 36,
      "category": "typography"
    },
    {
      "name": "body/lg/font-size",
      "value": 18,
      "category": "typography"
    },
    {
      "name": "body/lg/line-height",
      "value": 28,
      "category": "typography"
    },
    {
      "name": "body/md/font-size",
      "value": 16,
      "category": "typography"
    },
    {
      "name": "body/sm/font-size",
      "value": 14,
      "category": "typography"
    },
    {
      "name": "body/sm/line-height (l-16)",
      "value": 16,
      "category": "typography"
    },
    {
      "name": "body/sm/line-height (l-20)",
      "value": 20,
      "category": "typography"
    },
    {
      "name": "body/md/line-height (24)",
      "value": 24,
      "category": "typography"
    },
    {
      "name": "body/md/line-height (20)",
      "value": 20,
      "category": "typography"
    },
    {
      "name": "body/xs/font-size",
      "value": 12,
      "category": "typography"
    },
    {
      "name": "body/xs/line-height",
      "value": 18,
      "category": "typography"
    },
    {
      "name": "heading/H5/font-size",
      "value": 20,
      "category": "typography"
    },
    {
      "name": "heading/H5/line-height",
      "value": 28,
      "category": "typography"
    },
    {
      "name": "body/xxs/font-size",
      "value": 10,
      "category": "typography"
    },
    {
      "name": "body/xxs/line-height",
      "value": 14,
      "category": "typography"
    },
    {
      "name": "Opacity/Hover",
      "value": 8,
      "category": "Opacity"
    },
    {
      "name": "Opacity/Focus",
      "value": 12,
      "category": "Opacity"
    },
    {
      "name": "Opacity/Pressed",
      "value": 16,
      "category": "Opacity"
    },
    {
      "name": "Opacity/Disabled",
      "value": 38,
      "category": "Opacity"
    },
    {
      "name": "Opacity/Overlay",
      "value": 50,
      "category": "Opacity"
    }
  ],
  "gradients": [
    {
      "name": "Misc/Social ring",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0,
          "color": "#E09B3D",
          "opacity": 1
        },
        {
          "position": 0.3,
          "color": "#C74C4D",
          "opacity": 1
        },
        {
          "position": 0.6,
          "color": "#C21975",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#7024C4",
          "opacity": 1
        }
      ]
    }
  ],
  "aliases": {
    "colors": {
      "primary": "background/primary/bold_100",
      "secondary": "",
      "success": "background/success/bold_100",
      "warning": "background/warning/bold_100",
      "danger": "background/danger/bold_100",
      "background": "background/white/base",
      "surface": "surface/base",
      "textMain": "text/neutral/base",
      "textMuted": "text/neutral/subtle_500",
      "borderDivider": "border/neutral/subtle_400"
    },
    "typography": {
      "heading1": "H1/Regular",
      "heading2": "H2/Regular",
      "heading3": "H3/Regular",
      "heading4": "H4/Regular",
      "bodyLarge": "Text-lg/Regular",
      "bodyRegular": "Text-md (l-24)/Regular",
      "bodySmall": "Text-sm (l-20)/Regular",
      "caption": "Text-xs/Regular",
      "label": "Text-xxs/Regular",
      "code": ""
    },
    "radii": {
      "none": "border-radius/none",
      "small": "border-radius/sm",
      "medium": "border-radius/md",
      "large": "border-radius/lg",
      "round": "border-radius/full"
    },
    "shadows": {
      "none": "",
      "small": "",
      "medium": "",
      "large": "",
      "inner": ""
    },
    "borders": {
      "thin": "border/neutral/subtle_100",
      "medium": "border/neutral/subtle_300",
      "thick": "border/neutral/bold_100"
    },
    "spacing": {
      "md": "",
      "pagePadding": "",
      "containerGap": ""
    },
    "opacity": {
      "muted": "fixed/white/alpha-60",
      "disabled": "fixed/white/alpha-30"
    },
    "components": {
      "Button": {
        "background": "background/primary/bold_100",
        "color": "text/white/base"
      },
      "Input": {
        "border": "border/neutral/subtle_300"
      }
    }
  }
} as any;

export const designTokens = {
  colors: {
    /** #000000 */
    surfaceElavateL1: "#000000",
    /** #000000 */
    surfaceElavateL2: "#000000",
    /** #000000 */
    surfaceBase: "#000000",
    /** #000000 */
    surfaceBold100: "#000000",
    /** #000000 */
    surfaceBold200: "#000000",
    /** #000000 */
    backgroundWhiteBase: "#000000",
    /** #000000 */
    backgroundBlackBase: "#000000",
    /** #000000 */
    surfaceBold300: "#000000",
    /** #000000 */
    backgroundNeutralSubtle400: "#000000",
    /** #000000 */
    backgroundNeutralSubtle300: "#000000",
    /** #000000 */
    backgroundNeutralSubtle200: "#000000",
    /** #000000 */
    backgroundNeutralSubtle100: "#000000",
    /** #000000 */
    backgroundNeutralBold100: "#000000",
    /** #000000 */
    backgroundNeutralBold200: "#000000",
    /** #000000 */
    backgroundNeutralBold300: "#000000",
    /** #000000 */
    backgroundNeutralBold400: "#000000",
    /** #000000 */
    backgroundPrimarySubtle300: "#000000",
    /** #000000 */
    backgroundPrimarySubtle200: "#000000",
    /** #000000 */
    backgroundPrimarySubtle100: "#000000",
    /** #000000 */
    backgroundPrimaryBold100: "#000000",
    /** #000000 */
    backgroundPrimaryBold200: "#000000",
    /** #000000 */
    backgroundPrimaryBold300: "#000000",
    /** #000000 */
    backgroundDangerSubtle200: "#000000",
    /** #000000 */
    backgroundDangerSubtle100: "#000000",
    /** #000000 */
    iconWhiteBase: "#000000",
    /** #000000 */
    textWhiteBase: "#000000",
    /** #000000 */
    textNeutralSubtle500: "#000000",
    /** #000000 */
    textNeutralSubtle300: "#000000",
    /** #000000 */
    textNeutralSubtle200: "#000000",
    /** #000000 */
    textNeutralSubtle100: "#000000",
    /** #000000 */
    textNeutralBase: "#000000",
    /** #000000 */
    textPrimarySubtle200: "#000000",
    /** #000000 */
    textPrimarySubtle100: "#000000",
    /** #000000 */
    textPrimaryBase: "#000000",
    /** #000000 */
    textPrimaryBold100: "#000000",
    /** #000000 */
    textPrimaryBold200: "#000000",
    /** #000000 */
    textDangerBase: "#000000",
    /** #000000 */
    textDangerBold100: "#000000",
    /** #000000 */
    textInfoBase: "#000000",
    /** #000000 */
    textInfoBold100: "#000000",
    /** #000000 */
    textSuccessBase: "#000000",
    /** #000000 */
    textSuccessBold100: "#000000",
    /** #000000 */
    textWarningBase: "#000000",
    /** #000000 */
    textWarningBold100: "#000000",
    /** #000000 */
    iconNeutralSubtle500: "#000000",
    /** #000000 */
    backgroundDangerBold100: "#000000",
    /** #000000 */
    iconNeutralSubtle300: "#000000",
    /** #000000 */
    iconNeutralSubtle200: "#000000",
    /** #000000 */
    backgroundDangerBold200: "#000000",
    /** #000000 */
    iconNeutralSubtle100: "#000000",
    /** #000000 */
    iconNeutralBase: "#000000",
    /** #000000 */
    backgroundInfoSubtle200: "#000000",
    /** #000000 */
    backgroundInfoSubtle100: "#000000",
    /** #000000 */
    backgroundInfoBold100: "#000000",
    /** #000000 */
    borderWhiteBase: "#000000",
    /** #000000 */
    borderNeutralSubtle400: "#000000",
    /** #000000 */
    backgroundInfoBold200: "#000000",
    /** #000000 */
    borderNeutralSubtle300: "#000000",
    /** #000000 */
    iconPrimarySubtle200: "#000000",
    /** #000000 */
    iconPrimarySubtle100: "#000000",
    /** #000000 */
    iconPrimaryBase: "#000000",
    /** #000000 */
    iconPrimaryBold100: "#000000",
    /** #000000 */
    borderNeutralSubtle200: "#000000",
    /** #000000 */
    backgroundSuccessSubtle200: "#000000",
    /** #000000 */
    backgroundSuccessSubtle100: "#000000",
    /** #000000 */
    borderNeutralSubtle100: "#000000",
    /** #000000 */
    backgroundSuccessBold100: "#000000",
    /** #000000 */
    backgroundSuccessBold200: "#000000",
    /** #000000 */
    borderPrimarySubtle300: "#000000",
    /** #000000 */
    borderPrimarySubtle200: "#000000",
    /** #000000 */
    borderPrimarySubtle100: "#000000",
    /** #000000 */
    borderPrimaryBold100: "#000000",
    /** #000000 */
    borderPrimaryBold200: "#000000",
    /** #000000 */
    backgroundWarningSubtle200: "#000000",
    /** #000000 */
    borderNeutralBold100: "#000000",
    /** #000000 */
    borderNeutralBold200: "#000000",
    /** #000000 */
    backgroundWarningSubtle100: "#000000",
    /** #000000 */
    backgroundWarningBold100: "#000000",
    /** #000000 */
    backgroundWarningBold200: "#000000",
    /** #000000 */
    backgroundStateInteractionHoverNeutral: "#000000",
    /** #000000 */
    backgroundStateInteractionHoverPrimary: "#000000",
    /** #000000 */
    backgroundStateInteractionHoverDanger: "#000000",
    /** #000000 */
    backgroundStateInteractionHoverWhite: "#000000",
    /** #000000 */
    backgroundStateInteractionSelectedNeutral: "#000000",
    /** #000000 */
    backgroundStateInteractionDisabledNeutral: "#000000",
    /** #000000 */
    backgroundOverlayLight60: "#000000",
    /** #000000 */
    backgroundOverlayLight75: "#000000",
    /** #000000 */
    fixedWhiteBase: "#000000",
    /** #000000 */
    fixedWhiteAlpha30: "#000000",
    /** #000000 */
    fixedWhiteAlpha60: "#000000",
    /** #000000 */
    fixedWhiteAlpha75: "#000000",
    /** #000000 */
    fixedBlackBase: "#000000",
    /** #000000 */
    fixedBlackAlpha30: "#000000",
    /** #000000 */
    fixedBlackAlpha60: "#000000",
    /** #000000 */
    fixedBlackAlpha75: "#000000",
    /** #000000 */
    fixedNeutral50: "#000000",
    /** #000000 */
    fixedNeutral100: "#000000",
    /** #000000 */
    fixedNeutral200: "#000000",
    /** #000000 */
    fixedNeutral300: "#000000",
    /** #000000 */
    fixedNeutral400: "#000000",
    /** #000000 */
    fixedNeutral500: "#000000",
    /** #000000 */
    fixedNeutral600: "#000000",
    /** #000000 */
    fixedNeutral800: "#000000",
    /** #000000 */
    fixedNeutral900: "#000000",
    /** #000000 */
    fixedPrimary50: "#000000",
    /** #000000 */
    fixedPrimary100: "#000000",
    /** #000000 */
    fixedPrimary200: "#000000",
    /** #000000 */
    fixedPrimary250: "#000000",
    /** #000000 */
    fixedPrimary300: "#000000",
    /** #000000 */
    fixedPrimary400: "#000000",
    /** #000000 */
    fixedPrimary500: "#000000",
    /** #000000 */
    fixedDanger50: "#000000",
    /** #000000 */
    fixedPrimary600: "#000000",
    /** #000000 */
    fixedPrimary700: "#000000",
    /** #000000 */
    fixedDanger100: "#000000",
    /** #000000 */
    fixedDanger200: "#000000",
    /** #000000 */
    fixedDanger300: "#000000",
    /** #000000 */
    fixedDanger400: "#000000",
    /** #000000 */
    fixedDanger500: "#000000",
    /** #000000 */
    fixedInfo50: "#000000",
    /** #000000 */
    fixedDanger600: "#000000",
    /** #000000 */
    fixedDanger700: "#000000",
    /** #000000 */
    fixedInfo100: "#000000",
    /** #000000 */
    fixedInfo200: "#000000",
    /** #000000 */
    fixedInfo300: "#000000",
    /** #000000 */
    fixedInfo400: "#000000",
    /** #000000 */
    fixedInfo500: "#000000",
    /** #000000 */
    fixedInfo600: "#000000",
    /** #000000 */
    fixedInfo700: "#000000",
    /** #000000 */
    fixedSuccess50: "#000000",
    /** #000000 */
    fixedSuccess100: "#000000",
    /** #000000 */
    fixedSuccess200: "#000000",
    /** #000000 */
    fixedSuccess300: "#000000",
    /** #000000 */
    fixedSuccess400: "#000000",
    /** #000000 */
    fixedSuccess500: "#000000",
    /** #000000 */
    fixedSuccess600: "#000000",
    /** #000000 */
    fixedSuccess700: "#000000",
    /** #000000 */
    fixedWarning50: "#000000",
    /** #000000 */
    fixedWarning100: "#000000",
    /** #000000 */
    fixedWarning200: "#000000",
    /** #000000 */
    fixedWarning300: "#000000",
    /** #000000 */
    fixedWarning400: "#000000",
    /** #000000 */
    fixedWarning500: "#000000",
    /** #000000 */
    fixedWarning600: "#000000",
    /** #000000 */
    fixedWarning700: "#000000",
    /** #000000 */
    miscStatusOffline: "#000000",
    /** #000000 */
    miscStatusOnline: "#000000",
    /** #000000 */
    borderDangerSubtle300: "#000000",
    /** #000000 */
    borderDangerSubtle200: "#000000",
    /** #000000 */
    borderDangerSubtle100: "#000000",
    /** #000000 */
    borderDangerBold100: "#000000",
    /** #000000 */
    borderInfoSubtle300: "#000000",
    /** #000000 */
    borderInfoSubtle200: "#000000",
    /** #000000 */
    borderDangerBold200: "#000000",
    /** #000000 */
    borderInfoSubtle100: "#000000",
    /** #000000 */
    borderInfoBold100: "#000000",
    /** #000000 */
    borderInfoBold200: "#000000",
    /** #000000 */
    borderSuccessSubtle300: "#000000",
    /** #000000 */
    borderSuccessSubtle200: "#000000",
    /** #000000 */
    borderSuccessSubtle100: "#000000",
    /** #000000 */
    borderSuccessBold100: "#000000",
    /** #000000 */
    borderWarningSubtle300: "#000000",
    /** #000000 */
    borderWarningSubtle200: "#000000",
    /** #000000 */
    borderSuccessBold200: "#000000",
    /** #000000 */
    borderWarningSubtle100: "#000000",
    /** #000000 */
    borderWarningBold100: "#000000",
    /** #000000 */
    borderWarningBold200: "#000000",
    /** #000000 */
    iconDangerSubtle100: "#000000",
    /** #000000 */
    iconDangerBase: "#000000",
    /** #000000 */
    iconInfoSubtle200: "#000000",
    /** #000000 */
    iconDangerBold100: "#000000",
    /** #000000 */
    iconInfoSubtle100: "#000000",
    /** #000000 */
    iconInfoBase: "#000000",
    /** #000000 */
    iconInfoBold100: "#000000",
    /** #000000 */
    iconSuccessSubtle100: "#000000",
    /** #000000 */
    iconSuccessBase: "#000000",
    /** #000000 */
    iconSuccessBold100: "#000000",
    /** #000000 */
    iconWarningSubtle100: "#000000",
    /** #000000 */
    iconWarningBase: "#000000",
    /** #000000 */
    iconWarningBold100: "#000000",
    /** #000000 */
    borderNeutralBold300: "#000000",
    /** #000000 */
    borderNeutralBold400: "#000000",
    /** #000000 */
    backgroundOverlayDark60: "#000000",
    /** #000000 */
    backgroundOverlayDark75: "#000000",
    /** #000000 */
    surfaceOnSurfaceBase: "#000000",
    /** #000000 */
    surfaceOnSurfaceBold100: "#000000",
    /** #000000 */
    surfaceOnSurfaceBold200: "#000000",
    /** #FFFFFF */
    colorWhiteBaseFFFFFF: "#FFFFFF",
    /** #FFFFFF */
    colorWhiteAlpha30FFFFFF30: "#FFFFFF",
    /** #FFFFFF */
    colorWhiteAlpha60FFFFFF60: "#FFFFFF",
    /** #FFFFFF */
    colorWhiteAlpha75FFFFFF75: "#FFFFFF",
    /** #101114 */
    colorBlackBase121212: "#101114",
    /** #000000 */
    colorBlackAlpha3012121230: "#000000",
    /** #000000 */
    colorBlackAlpha6012121260: "#000000",
    /** #000000 */
    colorBlackAlpha7512121275: "#000000",
    /** #FCFCFD */
    colorNeutral50FCFCFD: "#FCFCFD",
    /** #F2F4F7 */
    colorNeutral100F2F4F7: "#F2F4F7",
    /** #E4E7EC */
    colorNeutral200E4E7EC: "#E4E7EC",
    /** #D0D5DD */
    colorNeutral300D0D5DD: "#D0D5DD",
    /** #8B939F */
    colorNeutral400ABB1BA: "#8B939F",
    /** #6E7581 */
    colorNeutral5007A7F89: "#6E7581",
    /** #40444D */
    colorNeutral60040444D: "#40444D",
    /** #282B31 */
    colorNeutral700282B31: "#282B31",
    /** #1D1F23 */
    colorNeutral8001D1F23: "#1D1F23",
    /** #17181A */
    colorNeutral90017181C: "#17181A",
    /** #ECF4FC */
    colorPrimary50ECF4FC: "#ECF4FC",
    /** #D8E9F9 */
    colorPrimary100D8E9F9: "#D8E9F9",
    /** #86C3F9 */
    colorPrimary20086C3F9: "#86C3F9",
    /** #65ABF1 */
    colorPrimary25065ABF1: "#65ABF1",
    /** #4B96E7 */
    colorPrimary3004B96E7: "#4B96E7",
    /** #0354A6 */
    colorPrimary4000354A6: "#0354A6",
    /** #064280 */
    colorPrimary500064280: "#064280",
    /** #012242 */
    colorPrimary600012242: "#012242",
    /** #011121 */
    colorPrimary700011121: "#011121",
    /** #FEF3F2 */
    colorDanger50FEF3F2: "#FEF3F2",
    /** #FDE1E1 */
    colorDanger100FDE1E1: "#FDE1E1",
    /** #FCA5A5 */
    colorDanger200FCA5A5: "#FCA5A5",
    /** #ED7D75 */
    colorDanger300ED7D75: "#ED7D75",
    /** #BB251A */
    colorDanger400BB251A: "#BB251A",
    /** #831A12 */
    colorDanger500831A12: "#831A12",
    /** #4B0F0A */
    colorDanger6004B0F0A: "#4B0F0A",
    /** #250705 */
    colorDanger700250705: "#250705",
    /** #EEF8FB */
    colorInfo50F1F7FD: "#EEF8FB",
    /** #DAF0F6 */
    colorInfo100DCEDFC: "#DAF0F6",
    /** #7DD1E8 */
    colorInfo20084CAFF: "#7DD1E8",
    /** #2E9AB8 */
    colorInfo30053A1EB: "#2E9AB8",
    /** #0E7B9B */
    colorInfo4001465B4: "#0E7B9B",
    /** #0A5A70 */
    colorInfo5000C3D6C: "#0A5A70",
    /** #093F4E */
    colorInfo6000A335A: "#093F4E",
    /** #05252E */
    colorInfo700061E36: "#05252E",
    /** #EFFFF8 */
    colorSuccess50EFFFF8: "#EFFFF8",
    /** #D8F3E7 */
    colorSuccess100D6F3E9: "#D8F3E7",
    /** #79D7AC */
    colorSuccess20079D7AC: "#79D7AC",
    /** #35AD77 */
    colorSuccess30035AD77: "#35AD77",
    /** #03834A */
    colorSuccess400039855: "#03834A",
    /** #045130 */
    colorSuccess500045130: "#045130",
    /** #012E19 */
    colorSuccess600012E19: "#012E19",
    /** #011E11 */
    colorSuccess700011E11: "#011E11",
    /** #FFF9F4 */
    colorWarning50FFF9F4: "#FFF9F4",
    /** #FCECD9 */
    colorWarning100FCF0DB: "#FCECD9",
    /** #FFC78F */
    colorWarning200FFC78F: "#FFC78F",
    /** #E7954F */
    colorWarning300E7954F: "#E7954F",
    /** #B45803 */
    colorWarning400DC6803: "#B45803",
    /** #7E3E07 */
    colorWarning5007F3004: "#7E3E07",
    /** #421F01 */
    colorWarning600421F01: "#421F01",
    /** #2C1501 */
    colorWarning7002C1501: "#2C1501",
    /** #0354A6 */
    colorMiscStateHoverPrimaryLight: "#0354A6",
    /** #5EAEFF */
    colorMiscStateHoverPrimaryDark: "#5EAEFF",
    /** #1D1F23 */
    colorMiscStateHoverGrayLight: "#1D1F23",
    /** #FCFCFD */
    colorMiscStateHoverGrayDark: "#FCFCFD",
    /** #FFFFFF */
    colorMiscStateHoverWhiteLight: "#FFFFFF",
    /** #FFFFFF */
    colorMiscStateHoverWhiteDark: "#FFFFFF",
    /** #BB251A */
    colorMiscStateHoverDangerLight: "#BB251A",
    /** #ED7D75 */
    colorMiscStateHoverDangerDark: "#ED7D75",
    /** #17181C */
    colorMiscStateSelectedGrayLight: "#17181C",
    /** #FCFCFD */
    colorMiscStateSelectedGrayDark: "#FCFCFD",
    /** #17181C */
    colorMiscStateDisabledGrayLight: "#17181C",
    /** #FCFCFD */
    colorMiscStateDisabledGrayDark: "#FCFCFD",
    /** #F2F4F7 */
    colorOnSurface: "#F2F4F7",
    /** #101828 */
    miscHoverBgNeutral: "#101828",
    /** #000000 */
    brand500: "#000000",
    /** #000000 */
    actionPrimary: "#000000",
    /** #000000 */
    success500: "#000000",
    /** #000000 */
    warning500: "#000000",
    /** #000000 */
    danger500: "#000000",
    /** #000000 */
    background: "#000000",
    /** #000000 */
    surface: "#000000",
    /** #000000 */
    textMain: "#000000",
    /** #000000 */
    textMuted: "#000000",
    /** #000000 */
    borderDivider: "#000000",
    /** #D9D9D9 */
    brand100: "#D9D9D9",
    /** #666666 */
    brand300: "#666666",
    /** #000000 */
    brand700: "#000000",
    /** #FFFFFF */
    white: "#FFFFFF",
    /** #000000 */
    black: "#000000",
    /** #D1D5DB */
    neutral300: "#D1D5DB",
    /** #6b7280 */
    actionSecondary: "#6b7280",
  },
  typography: {
    h1Regular: {
      fontFamily: "Nunito Sans",
      fontSize: 36, /* dimension/36 - 2_25 rem */
      fontWeight: 400,
      lineHeight: 44, /* dimension/44 - 2_75 rem */
    },
    h1Bold: {
      fontFamily: "Nunito Sans",
      fontSize: 36, /* dimension/36 - 2_25 rem */
      fontWeight: 700,
      lineHeight: 44, /* dimension/44 - 2_75 rem */
    },
    h2Regular: {
      fontFamily: "Nunito Sans",
      fontSize: 32, /* dimension/32 - 2 rem */
      fontWeight: 400,
      lineHeight: 40, /* dimension/40 - 2_5 rem */
    },
    h2Bold: {
      fontFamily: "Nunito Sans",
      fontSize: 32, /* dimension/32 - 2 rem */
      fontWeight: 700,
      lineHeight: 40, /* dimension/40 - 2_5 rem */
    },
    h3Regular: {
      fontFamily: "Nunito Sans",
      fontSize: 28, /* dimension/28 - 1_75 rem */
      fontWeight: 400,
      lineHeight: 36, /* dimension/36 - 2_25 rem */
    },
    h3Bold: {
      fontFamily: "Nunito Sans",
      fontSize: 28, /* dimension/28 - 1_75 rem */
      fontWeight: 700,
      lineHeight: 36, /* dimension/36 - 2_25 rem */
    },
    h4Regular: {
      fontFamily: "Nunito Sans",
      fontSize: 24, /* dimension/24 - 1_5 rem */
      fontWeight: 400,
      lineHeight: 32, /* dimension/32 - 2 rem */
    },
    h4Bold: {
      fontFamily: "Nunito Sans",
      fontSize: 24, /* dimension/24 - 1_5 rem */
      fontWeight: 700,
      lineHeight: 32, /* dimension/32 - 2 rem */
    },
    h5Regular: {
      fontFamily: "Nunito Sans",
      fontSize: 20, /* dimension/20 - 1_25 rem */
      fontWeight: 400,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    h5Bold: {
      fontFamily: "Nunito Sans",
      fontSize: 20, /* dimension/20 - 1_25 rem */
      fontWeight: 700,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    textLgRegular: {
      fontFamily: "Inter",
      fontSize: 18, /* dimension/18 - 1_125 rem */
      fontWeight: 400,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    textLgMedium: {
      fontFamily: "Inter",
      fontSize: 18, /* dimension/18 - 1_125 rem */
      fontWeight: 500,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    textLgSemibold: {
      fontFamily: "Inter",
      fontSize: 18, /* dimension/18 - 1_125 rem */
      fontWeight: 600,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    textLgRegularUnderline: {
      fontFamily: "Inter",
      fontSize: 18, /* dimension/18 - 1_125 rem */
      fontWeight: 400,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    textLgMediumUnderline: {
      fontFamily: "Inter",
      fontSize: 18, /* dimension/18 - 1_125 rem */
      fontWeight: 500,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    textMdl24Regular: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 400,
      lineHeight: 24, /* dimension/24 - 1_5 rem */
    },
    textMdl24Medium: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 500,
      lineHeight: 24, /* dimension/24 - 1_5 rem */
    },
    textMdl24Semibold: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 600,
      lineHeight: 24, /* dimension/24 - 1_5 rem */
    },
    textMdl24RegularUnderline: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 400,
      lineHeight: 24, /* dimension/24 - 1_5 rem */
    },
    textMdl24MediumUnderline: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 500,
      lineHeight: 24, /* dimension/24 - 1_5 rem */
    },
    textMdl20Regular: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 400,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textMdl20Medium: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 500,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textMdl20Semibold: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 600,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textMdl20RegularUnderline: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 400,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textMdl20MediumUnderline: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 500,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textSml20Regular: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 400,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textSml20Medium: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 500,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textSml20Semibold: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 600,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textSml20RegularUnderline: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 400,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textSml20MediumUnderline: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 500,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    textSml16Regular: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 400,
      lineHeight: 16, /* dimension/16 - 1 rem */
    },
    textSml16Medium: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 500,
      lineHeight: 16, /* dimension/16 - 1 rem */
    },
    textSml16Semibold: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 600,
      lineHeight: 16, /* dimension/16 - 1 rem */
    },
    textSml16RegularUnderline: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 400,
      lineHeight: 16, /* dimension/16 - 1 rem */
    },
    textSml16MediumUnderline: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 500,
      lineHeight: 16, /* dimension/16 - 1 rem */
    },
    textXsRegular: {
      fontFamily: "Inter",
      fontSize: 12, /* dimension/12 - 0_75 rem */
      fontWeight: 400,
      lineHeight: 18, /* dimension/18 - 1_125 rem */
    },
    textXsMedium: {
      fontFamily: "Inter",
      fontSize: 12, /* dimension/12 - 0_75 rem */
      fontWeight: 500,
      lineHeight: 18, /* dimension/18 - 1_125 rem */
    },
    textXsSemibold: {
      fontFamily: "Inter",
      fontSize: 12, /* dimension/12 - 0_75 rem */
      fontWeight: 600,
      lineHeight: 18, /* dimension/18 - 1_125 rem */
    },
    textXsRegularUnderline: {
      fontFamily: "Inter",
      fontSize: 12, /* dimension/12 - 0_75 rem */
      fontWeight: 400,
      lineHeight: 18, /* dimension/18 - 1_125 rem */
    },
    textXsMediumUnderline: {
      fontFamily: "Inter",
      fontSize: 12, /* dimension/12 - 0_75 rem */
      fontWeight: 500,
      lineHeight: 18, /* dimension/18 - 1_125 rem */
    },
    textXxsRegular: {
      fontFamily: "Inter",
      fontSize: 10, /* dimension/10 - 0_625 rem */
      fontWeight: 400,
      lineHeight: 14, /* dimension/14 - 0_875 rem */
    },
    textXxsMedium: {
      fontFamily: "Inter",
      fontSize: 10, /* dimension/10 - 0_625 rem */
      fontWeight: 500,
      lineHeight: 14, /* dimension/14 - 0_875 rem */
    },
    textXxsSemibold: {
      fontFamily: "Inter",
      fontSize: 10, /* dimension/10 - 0_625 rem */
      fontWeight: 600,
      lineHeight: 14, /* dimension/14 - 0_875 rem */
    },
    textXxsRegularUnderline: {
      fontFamily: "Inter",
      fontSize: 10, /* dimension/10 - 0_625 rem */
      fontWeight: 400,
      lineHeight: 14, /* dimension/14 - 0_875 rem */
    },
    textXxsMediumUnderline: {
      fontFamily: "Inter",
      fontSize: 10, /* dimension/10 - 0_625 rem */
      fontWeight: 500,
      lineHeight: 14, /* dimension/14 - 0_875 rem */
    },
    heading1: {
      fontFamily: "Nunito Sans",
      fontSize: 36, /* dimension/36 - 2_25 rem */
      fontWeight: 400,
      lineHeight: 44, /* dimension/44 - 2_75 rem */
    },
    heading2: {
      fontFamily: "Nunito Sans",
      fontSize: 32, /* dimension/32 - 2 rem */
      fontWeight: 400,
      lineHeight: 40, /* dimension/40 - 2_5 rem */
    },
    heading3: {
      fontFamily: "Nunito Sans",
      fontSize: 28, /* dimension/28 - 1_75 rem */
      fontWeight: 400,
      lineHeight: 36, /* dimension/36 - 2_25 rem */
    },
    bodyLarge: {
      fontFamily: "Inter",
      fontSize: 18, /* dimension/18 - 1_125 rem */
      fontWeight: 400,
      lineHeight: 28, /* dimension/28 - 1_75 rem */
    },
    bodyRegular: {
      fontFamily: "Inter",
      fontSize: 16, /* dimension/16 - 1 rem */
      fontWeight: 400,
      lineHeight: 24, /* dimension/24 - 1_5 rem */
    },
    bodySmall: {
      fontFamily: "Inter",
      fontSize: 14, /* dimension/14 - 0_875 rem */
      fontWeight: 400,
      lineHeight: 20, /* dimension/20 - 1_25 rem */
    },
    caption: {
      fontFamily: "Inter",
      fontSize: 12, /* dimension/12 - 0_75 rem */
      fontWeight: 400,
      lineHeight: 18, /* dimension/18 - 1_125 rem */
    },
  },
  radius: {
    borderRadiusNone: { topLeft: 0, topRight: 0, bottomRight: 0, bottomLeft: 0 },
    borderRadiusXs: { topLeft: 4, topRight: 4, bottomRight: 4, bottomLeft: 4 },
    borderRadiusSm: { topLeft: 6, topRight: 6, bottomRight: 6, bottomLeft: 6 },
    borderRadiusMd: { topLeft: 8, topRight: 8, bottomRight: 8, bottomLeft: 8 },
    borderRadiusLg: { topLeft: 12, topRight: 12, bottomRight: 12, bottomLeft: 12 },
    borderRadiusXl: { topLeft: 16, topRight: 16, bottomRight: 16, bottomLeft: 16 },
    borderRadius2xl: { topLeft: 24, topRight: 24, bottomRight: 24, bottomLeft: 24 },
    borderRadius3xl: { topLeft: 32, topRight: 32, bottomRight: 32, bottomLeft: 32 },
    borderRadiusFull: { topLeft: 9999, topRight: 9999, bottomRight: 9999, bottomLeft: 9999 },
    small: { topLeft: 6, topRight: 6, bottomRight: 6, bottomLeft: 6 },
    medium: { topLeft: 8, topRight: 8, bottomRight: 8, bottomLeft: 8 },
    large: { topLeft: 12, topRight: 12, bottomRight: 12, bottomLeft: 12 },
    round: { topLeft: 9999, topRight: 9999, bottomRight: 9999, bottomLeft: 9999 },
  },
  gradients: {
    miscSocialRing: {"type":"linear","stops":[{"position":0,"color":"#E09B3D","opacity":1},{"position":0.3,"color":"#C74C4D","opacity":1},{"position":0.6,"color":"#C21975","opacity":1},{"position":1,"color":"#7024C4","opacity":1}]},
  },
  gaps: {
    headingH2LetterSpacing: -0.019999999552965164,
    headingH2ParagaphSpacing: 28,
    headingH1LetterSpacing: -0.019999999552965164,
    headingH1ParagaphSpacing: 32,
    headingH4LetterSpacing: 0,
    headingH4ParagaphSpacing: 20,
    headingH3LetterSpacing: -0.019999999552965164,
    headingH3ParagaphSpacing: 24,
    bodyLgLetterSpacing: 0,
    bodyLgParagaphSpacing: 24,
    bodySmLetterSpacing: 0,
    bodySmParagaphSpacing: 16,
    bodyMdLetterSpacing: 0,
    bodyMdParagaphSpacing: 20,
    bodyXsLetterSpacing: 0.009999999776482582,
    bodyXsParagaphSpacing: 12,
    headingH5LetterSpacing: 0,
    headingH5ParagaphSpacing: 16,
    bodyXxsLetterSpacing: 0.019999999552965164,
    bodyXxsParagaphSpacing: 8,
  },
  sizes: {
    fontWeightRegular400: 400,
    dimensionNull: 0,
    dimension4025Rem: 4,
    dimension60375Rem: 6,
    dimension805Rem: 8,
    dimension100625Rem: 10,
    dimension12075Rem: 12,
    dimension140875Rem: 14,
    dimension161Rem: 16,
    dimension181125Rem: 18,
    dimension20125Rem: 20,
    dimension2415Rem: 24,
    dimension28175Rem: 28,
    dimension322Rem: 32,
    dimension36225Rem: 36,
    dimension4025Rem1: 40,
    dimension44275Rem: 44,
    dimension5635Rem: 56,
    dimension644Rem: 64,
    dimension805Rem1: 80,
    dimension966Rem: 96,
    dimensionFull: 999,
    fontWeightMedium500: 500,
    fontWeightSemibold600: 600,
    fontWeightBold700: 700,
    fontWeightExtrabold800: 800,
    borderWidthNone: 0,
    borderWidthThin: 1,
    borderWidthMedium: 2,
    borderWidthThick: 4,
    headingH1FontSize: 36,
    headingH2FontSize: 32,
    headingH2LineHeight: 40,
    headingH1LineHeight: 44,
    headingH3FontSize: 28,
    headingH4FontSize: 24,
    headingH4LineHeight: 32,
    headingH3LineHeight: 36,
    bodyLgFontSize: 18,
    bodyLgLineHeight: 28,
    bodyMdFontSize: 16,
    bodySmFontSize: 14,
    bodySmLineHeightl16: 16,
    bodySmLineHeightl20: 20,
    bodyMdLineHeight24: 24,
    bodyMdLineHeight20: 20,
    bodyXsFontSize: 12,
    bodyXsLineHeight: 18,
    headingH5FontSize: 20,
    headingH5LineHeight: 28,
    bodyXxsFontSize: 10,
    bodyXxsLineHeight: 14,
    opacityHover: 8,
    opacityFocus: 12,
    opacityPressed: 16,
    opacityDisabled: 38,
    opacityOverlay: 50,
  },
} as const;

export type DesignTokens = typeof designTokens;
export type ColorKey = keyof typeof designTokens.colors;
export type TypographyKey = keyof typeof designTokens.typography;
export type RadiusKey = keyof typeof designTokens.radius;
export type GapKey = keyof typeof designTokens.gaps;
export type SizeKey = keyof typeof designTokens.sizes;
