/* Auto-generated by Guing — do not edit manually */

export const tokens = {
  "colors": [
    {
      "name": "Body-text-Frame-2147225184-Default",
      "value": "#295365",
      "category": "Frame 2147225184/Default"
    },
    {
      "name": "Body-text-Buttons",
      "value": "#1D1D1D",
      "category": "Buttons"
    },
    {
      "name": "Icons",
      "value": "#D7E3EC",
      "category": "New buttons / Group"
    },
    {
      "name": "Buttons",
      "value": "#191836",
      "category": "New buttons / Secondary button"
    },
    {
      "name": "grey-page-1",
      "value": "#091C2A",
      "category": "Colors"
    },
    {
      "name": "grey-page-2",
      "value": "#051321",
      "category": "General"
    },
    {
      "name": "Disabled",
      "value": "#505D6F",
      "category": "New buttons / Primary button"
    },
    {
      "name": "Disabled-text",
      "value": "#6C7683",
      "category": "New buttons / Confirm / state=disabled, icon=false"
    },
    {
      "name": "Figma-section",
      "value": "#232D42",
      "category": "General"
    },
    {
      "name": "Grey-100",
      "value": "#EFEFEF",
      "category": "Menu/Action Item - Single"
    },
    {
      "name": "Grey-500",
      "value": "#7C7C7C",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / Done / Icon / Done"
    },
    {
      "name": "Grey-600-text",
      "value": "#656565",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / Done / note text"
    },
    {
      "name": "Header-Icons",
      "value": "#8E8EA9",
      "category": "Buttons / audiocodes-logo-svg (3) 2"
    },
    {
      "name": "Primary",
      "value": "#8A5ADB",
      "category": "Buttons"
    },
    {
      "name": "purple-purple",
      "value": "#9B5DFF",
      "category": "Colors"
    },
    {
      "name": "Red-Error",
      "value": "#EF355D",
      "category": "New buttons / icons"
    },
    {
      "name": "Selected-Secondary-button",
      "value": "#F0F0F0",
      "category": "New buttons / Secondary button"
    },
    {
      "name": "Selected-MenuList",
      "value": "#192557",
      "category": "New buttons / <Menu> / <Paper> / <MenuList>"
    },
    {
      "name": "Tag-Green-44DB95",
      "value": "#44DB95",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / all tabs / Planner / Monday / monday logo 1"
    },
    {
      "name": "Text-field",
      "value": "#2B344D",
      "category": "New buttons / <Menu>"
    },
    {
      "name": "white-white",
      "value": "#FFFFFF",
      "category": "Colors"
    },
    {
      "name": "blue-blue",
      "value": "#3074F3",
      "category": "Colors"
    },
    {
      "name": "green-green",
      "value": "#25A96B",
      "category": "Colors"
    },
    {
      "name": "grey-buttons-bg",
      "value": "#1B293A",
      "category": "Colors"
    },
    {
      "name": "grey-drawer-handle",
      "value": "#ADB4CA",
      "category": "Colors"
    },
    {
      "name": "grey-grey",
      "value": "#C9CFDC",
      "category": "Colors"
    },
    {
      "name": "grey-secondary-body-text",
      "value": "#90A3B1",
      "category": "Colors"
    },
    {
      "name": "grey-stroke",
      "value": "#2A4051",
      "category": "Colors"
    },
    {
      "name": "grey-text-field",
      "value": "#2F3649",
      "category": "Colors"
    },
    {
      "name": "orange-orange-warning",
      "value": "#FFA000",
      "category": "Colors"
    },
    {
      "name": "red-red-error",
      "value": "#C84747",
      "category": "Colors"
    },
    {
      "name": "red-red-warning",
      "value": "#FF4B4B",
      "category": "Colors"
    },
    {
      "name": "turquoise-turquoise",
      "value": "#00FFFF",
      "category": "Colors"
    }
  ],
  "typography": [
    {
      "name": "Primary",
      "fontFamily": "Inter",
      "fontSize": 64,
      "fontWeight": 600,
      "lineHeight": "normal",
      "category": "Buttons",
      "color": "#8A5ADB"
    },
    {
      "name": "Body-text",
      "fontFamily": "Inter",
      "fontSize": 20,
      "fontWeight": 500,
      "lineHeight": 1.25,
      "category": "Buttons",
      "color": "#1D1D1D"
    },
    {
      "name": "white-white-Status-Bar",
      "fontFamily": "SF Pro",
      "fontSize": 15,
      "fontWeight": 600,
      "lineHeight": "normal",
      "category": "componets / Navigation Bar / Property 1=Old / Status Bar",
      "color": "#FFFFFF",
      "letterSpacing": -0.17
    },
    {
      "name": "white-white-Container",
      "fontFamily": "SF Pro Text",
      "fontSize": 17,
      "fontWeight": 400,
      "lineHeight": "normal",
      "category": "componets / Navigation Bar / Property 1=Old / Status Bar / Container",
      "color": "#FFFFFF"
    },
    {
      "name": "white-white-Container-2",
      "fontFamily": "SF Pro Text",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": "normal",
      "category": "componets / Navigation Bar / Property 1=Old / Status Bar / Container",
      "color": "#FFFFFF"
    },
    {
      "name": "Grey-600-text",
      "fontFamily": "Segoe UI",
      "fontSize": 12,
      "fontWeight": 400,
      "lineHeight": 13,
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / Done / note text",
      "color": "#656565"
    },
    {
      "name": "16-Reg",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": 24,
      "category": "Frame 2147225184/Default",
      "color": "#295365"
    },
    {
      "name": "grey-text-icons",
      "fontFamily": "Heebo",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": "normal",
      "category": "componets / Navigation Bar / Property 1=Old",
      "color": "#D7E3EC",
      "textTransform": "capitalize"
    },
    {
      "name": "LabelSml",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 400,
      "lineHeight": "normal",
      "category": "componets / Inputs & Controls",
      "color": "#FFFFFF",
      "textTransform": "capitalize"
    },
    {
      "name": "Lable-Sami-12",
      "fontFamily": "Inter",
      "fontSize": 12,
      "fontWeight": 600,
      "lineHeight": "normal",
      "category": "componets / Menu / Property 1=Home / navigation",
      "color": "#FFFFFF",
      "textTransform": "capitalize"
    },
    {
      "name": "Inter-20-SemiBold",
      "fontFamily": "Inter",
      "fontSize": 20,
      "fontWeight": 600,
      "lineHeight": 1.25,
      "category": "New buttons",
      "color": "#1D1D1D"
    },
    {
      "name": "Button-text",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": 1.25,
      "category": "New buttons / Confirm / state=Default, icon=false",
      "color": "#8A5ADB",
      "letterSpacing": 1
    },
    {
      "name": "LabelLarge-14-Med",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": "normal",
      "category": "componets / Navigation Bar / Property 1=New / Icon + Text",
      "color": "#FFFFFF",
      "textTransform": "capitalize"
    },
    {
      "name": "LabelReg-14-Reg",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": "normal",
      "category": "componets / Label / Property 1=Default",
      "color": "#FFFFFF",
      "textTransform": "capitalize"
    },
    {
      "name": "HeadlineReg-16-Med",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 500,
      "lineHeight": "normal",
      "category": "componets / Button CTA / New Recording=Variant2",
      "color": "#FFFFFF",
      "textTransform": "capitalize"
    },
    {
      "name": "14-Regular",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 20,
      "category": "componets / Search Bar / Property 1=Search Bar - Back",
      "color": "#90A3B1"
    },
    {
      "name": "HeadlineMed-18-Med",
      "fontFamily": "Inter",
      "fontSize": 18,
      "fontWeight": 500,
      "lineHeight": "normal",
      "category": "componets / Popup",
      "color": "#D7E3EC",
      "textTransform": "capitalize"
    },
    {
      "name": "HeadlineReg-16-Reg",
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": 400,
      "lineHeight": "normal",
      "category": "componets / Popup",
      "color": "#D7E3EC",
      "textTransform": "capitalize"
    },
    {
      "name": "Body",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 400,
      "lineHeight": 1.25,
      "category": "New buttons",
      "color": "#7C88A6"
    },
    {
      "name": "Body-bold",
      "fontFamily": "Inter",
      "fontSize": 14,
      "fontWeight": 500,
      "lineHeight": 1.25,
      "category": "New buttons",
      "color": "#FFFFFF"
    }
  ],
  "radius": [
    {
      "name": "Radius-XXS",
      "value": 2,
      "topLeft": 2,
      "topRight": 2,
      "bottomRight": 2,
      "bottomLeft": 2,
      "category": "Size Token"
    },
    {
      "name": "Radius-XS",
      "value": 4,
      "topLeft": 4,
      "topRight": 4,
      "bottomRight": 4,
      "bottomLeft": 4,
      "category": "Size Token"
    },
    {
      "name": "Radius-S",
      "value": 8,
      "topLeft": 8,
      "topRight": 8,
      "bottomRight": 8,
      "bottomLeft": 8,
      "category": "Size Token"
    },
    {
      "name": "Radius-M",
      "value": 12,
      "topLeft": 12,
      "topRight": 12,
      "bottomRight": 12,
      "bottomLeft": 12,
      "category": "Size Token"
    },
    {
      "name": "Radius-L",
      "value": 16,
      "topLeft": 16,
      "topRight": 16,
      "bottomRight": 16,
      "bottomLeft": 16,
      "category": "Size Token"
    },
    {
      "name": "Radius-XL",
      "value": 20,
      "topLeft": 20,
      "topRight": 20,
      "bottomRight": 20,
      "bottomLeft": 20,
      "category": "Size Token"
    },
    {
      "name": "Radius-Full",
      "value": 99,
      "topLeft": 99,
      "topRight": 99,
      "bottomRight": 99,
      "bottomLeft": 99,
      "category": "Size Token"
    },
    {
      "name": "Menu",
      "value": 5,
      "topLeft": 5,
      "topRight": 5,
      "bottomRight": 5,
      "bottomLeft": 5,
      "category": "componets"
    },
    {
      "name": "Icons",
      "value": 1133.3333740234375,
      "topLeft": 1133.3333740234375,
      "topRight": 1133.3333740234375,
      "bottomRight": 1133.3333740234375,
      "bottomLeft": 1133.3333740234375,
      "category": "componets / Navigation Bar / Property 1=New"
    },
    {
      "name": "Rectangle-20",
      "value": 10,
      "topLeft": 10,
      "topRight": 10,
      "bottomRight": 10,
      "bottomLeft": 10,
      "category": "componets / Menu / Property 1=Home / navigation/menu - left"
    },
    {
      "name": "Icon-Done",
      "value": 30,
      "topLeft": 30,
      "topRight": 30,
      "bottomRight": 30,
      "bottomLeft": 30,
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / Done"
    },
    {
      "name": "Primary",
      "value": 156.69219970703125,
      "topLeft": 156.69219970703125,
      "topRight": 156.69219970703125,
      "bottomRight": 156.69219970703125,
      "bottomLeft": 156.69219970703125,
      "category": "New buttons / Secondary button / state=Default, icon=false"
    },
    {
      "name": "Rectangle",
      "value": 1.2000000476837158,
      "topLeft": 1.2000000476837158,
      "topRight": 1.2000000476837158,
      "bottomRight": 1.2000000476837158,
      "bottomLeft": 1.2000000476837158,
      "category": "componets / Navigation Bar / Property 1=Old / Status Bar / Container / Combined Shape"
    },
    {
      "name": "grey-buttons-bg",
      "value": 1400,
      "topLeft": 1400,
      "topRight": 1400,
      "bottomRight": 1400,
      "bottomLeft": 1400,
      "category": "componets / Navigation Bar / Property 1=Old"
    },
    {
      "name": "Rectangle-9",
      "value": 200,
      "topLeft": 200,
      "topRight": 200,
      "bottomRight": 200,
      "bottomLeft": 200,
      "category": "componets / Button CTA / New Recording=Variant2"
    },
    {
      "name": "grey-page",
      "value": 24,
      "topLeft": 24,
      "topRight": 24,
      "bottomRight": 24,
      "bottomLeft": 24,
      "category": "componets / Popup"
    },
    {
      "name": "Frame-1973342108",
      "value": 44.4444465637207,
      "topLeft": 44.4444465637207,
      "topRight": 44.4444465637207,
      "bottomRight": 44.4444465637207,
      "bottomLeft": 44.4444465637207,
      "category": "componets / Popup"
    },
    {
      "name": "tertiary",
      "value": 58,
      "topLeft": 58,
      "topRight": 58,
      "bottomRight": 58,
      "bottomLeft": 58,
      "category": "componets / Popup"
    }
  ],
  "shadows": [
    {
      "name": "Vector",
      "shadows": [
        {
          "type": "drop",
          "color": "#000000",
          "opacity": 0.25,
          "offsetX": 0,
          "offsetY": 4,
          "blur": 4,
          "spread": 0
        }
      ],
      "category": "componets / Icons / Property 1=Filter / Frame"
    },
    {
      "name": "Design system/Button shadow",
      "shadows": [
        {
          "type": "drop",
          "color": "#160532",
          "opacity": 0.2,
          "offsetX": 0,
          "offsetY": 1.5,
          "blur": 3,
          "spread": 0
        }
      ],
      "category": "New buttons"
    }
  ],
  "elevations": [
    {
      "name": "elevation/8",
      "shadows": [
        {
          "type": "drop",
          "color": "#000000",
          "opacity": 0.2,
          "offsetX": 0,
          "offsetY": 5,
          "blur": 5,
          "spread": -3
        },
        {
          "type": "drop",
          "color": "#000000",
          "opacity": 0.14,
          "offsetX": 0,
          "offsetY": 8,
          "blur": 10,
          "spread": 1
        },
        {
          "type": "drop",
          "color": "#000000",
          "opacity": 0.12,
          "offsetX": 0,
          "offsetY": 3,
          "blur": 14,
          "spread": 2
        }
      ],
      "category": "New buttons / <Menu>"
    }
  ],
  "borders": [
    {
      "name": "grey-page-Meeting-list-Item",
      "color": "#2A4051",
      "weight": 1,
      "strokeAlign": "INSIDE",
      "category": "componets / Meeting list - Item"
    },
    {
      "name": "grey-page-Property-1-Home",
      "color": "#2A4051",
      "weight": 1,
      "strokeAlign": "OUTSIDE",
      "category": "componets / Menu / Property 1=Home",
      "strokeCap": "ROUND"
    },
    {
      "name": "Menu",
      "color": "#8A38F5",
      "weight": 1,
      "strokeAlign": "INSIDE",
      "category": "componets",
      "dashPattern": [
        10,
        5
      ]
    },
    {
      "name": "Vector-Icons",
      "color": "#90A3B1",
      "weight": 1.5,
      "strokeAlign": "CENTER",
      "category": "componets / Navigation Bar / Property 1=New / Icons",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame",
      "color": "#FFFFFF",
      "weight": 1.25,
      "strokeAlign": "CENTER",
      "category": "componets / Inputs & Controls / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-navigation",
      "color": "#FFFFFF",
      "weight": 1.5833332538604736,
      "strokeAlign": "CENTER",
      "category": "componets / Menu / Property 1=Home / navigation",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-navigation-2",
      "color": "#FFFFFF",
      "weight": 1.5,
      "strokeAlign": "INSIDE",
      "category": "componets / Menu / Property 1=Meetings / navigation"
    },
    {
      "name": "Vector-Frame-2",
      "color": "#FFFFFF",
      "weight": 1,
      "strokeAlign": "CENTER",
      "category": "componets / Search Bar / Property 1=Search AI / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-3",
      "color": "#D7E3EC",
      "weight": 1.5,
      "strokeAlign": "CENTER",
      "category": "componets / Navigation Bar / Property 1=Old / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-4",
      "color": "#D7E3EC",
      "weight": 1.25,
      "strokeAlign": "CENTER",
      "category": "componets / Icons / Property 1=Filter / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-5",
      "color": "#FFFFFF",
      "weight": 1.5,
      "strokeAlign": "CENTER",
      "category": "componets / Button CTA / New Recording=Variant2 / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-6",
      "color": "#C84747",
      "weight": 1,
      "strokeAlign": "CENTER",
      "category": "componets / Meeting list - Item / Property 1=Variant2 / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-7",
      "color": "#FFFFFF",
      "weight": 1.0416666269302368,
      "strokeAlign": "CENTER",
      "category": "componets / Button Menu / Property 1=Done / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-8",
      "color": "#D7E3EC",
      "weight": 1.0416666269302368,
      "strokeAlign": "CENTER",
      "category": "componets / Button Menu / Property 1=edit / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-Frame-9",
      "color": "#FF4B4B",
      "weight": 1.25,
      "strokeAlign": "CENTER",
      "category": "componets / Button Menu / Property 1=Logout / Frame",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Vector-ai-search-02",
      "color": "#D7E3EC",
      "weight": 1.125,
      "strokeAlign": "CENTER",
      "category": "componets / Search Bar / Property 1=Search AI / ai-search-02",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    },
    {
      "name": "Icon-Done",
      "color": "#7C7C7C",
      "weight": 2,
      "strokeAlign": "INSIDE",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / Done"
    },
    {
      "name": "Line-10",
      "color": "#525C6D",
      "weight": 1,
      "strokeAlign": "CENTER",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs"
    },
    {
      "name": "Confirm",
      "color": "#9B5DFF",
      "weight": 1,
      "strokeAlign": "INSIDE",
      "category": "New buttons",
      "dashPattern": [
        10,
        5
      ]
    },
    {
      "name": "grey-buttons-bg",
      "color": "#2A4051",
      "weight": 1.1333333253860474,
      "strokeAlign": "INSIDE",
      "category": "componets / Navigation Bar / Property 1=New"
    },
    {
      "name": "Line-1",
      "color": "#90A3B1",
      "weight": 1,
      "strokeAlign": "CENTER",
      "category": "componets / Search Bar / Property 1=Search Bar - Back"
    },
    {
      "name": "Grey-500-Done",
      "color": "#7C7C7C",
      "weight": 2,
      "strokeAlign": "CENTER",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / Done / Icon / Done",
      "strokeCap": "ROUND"
    },
    {
      "name": "Grey-500-Group",
      "color": "#7C7C7C",
      "weight": 0.5,
      "strokeAlign": "CENTER",
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / e icon+e text / email icon / copy 2 / Group / Group"
    },
    {
      "name": "White",
      "color": "#000000",
      "weight": 1,
      "strokeAlign": "INSIDE",
      "category": "New buttons"
    },
    {
      "name": "Vector-1",
      "color": "#D7E3EC",
      "weight": 2,
      "strokeAlign": "CENTER",
      "category": "New buttons / Primary button",
      "strokeCap": "ROUND"
    },
    {
      "name": "Disabled",
      "color": "#505D6F",
      "weight": 1,
      "strokeAlign": "INSIDE",
      "category": "New buttons / Primary button"
    },
    {
      "name": "grey-text-icons-Frame",
      "color": "#D7E3EC",
      "weight": 1.1773462295532227,
      "strokeAlign": "INSIDE",
      "category": "componets / Navigation Bar / Property 1=Old / Frame"
    },
    {
      "name": "grey-text-icons-Frame-2",
      "color": "#FFFFFF",
      "weight": 1.1852092742919922,
      "strokeAlign": "INSIDE",
      "category": "componets / Navigation Bar / Property 1=New / Icon + Text / Frame"
    },
    {
      "name": "grey-text-icons-ai-search-02",
      "color": "#D7E3EC",
      "weight": 0.7499999403953552,
      "strokeAlign": "CENTER",
      "category": "componets / Search Bar / Property 1=Search AI / ai-search-02",
      "strokeCap": "ROUND",
      "strokeJoin": "ROUND"
    }
  ],
  "sizes": [
    {
      "name": "Space-XXS",
      "value": 4,
      "category": "Size Token"
    },
    {
      "name": "Space-XS",
      "value": 8,
      "category": "Size Token"
    },
    {
      "name": "Space-S",
      "value": 12,
      "category": "Size Token"
    },
    {
      "name": "Space-M",
      "value": 16,
      "category": "Size Token"
    },
    {
      "name": "Space-L",
      "value": 20,
      "category": "Size Token"
    },
    {
      "name": "Space-XL",
      "value": 24,
      "category": "Size Token"
    },
    {
      "name": "Space-XXL",
      "value": 32,
      "category": "Size Token"
    },
    {
      "name": "Space-XXXL",
      "value": 40,
      "category": "Size Token"
    },
    {
      "name": "Border-width-XXS",
      "value": 1,
      "category": "Size Token"
    },
    {
      "name": "Border-width-XS",
      "value": 1.25,
      "category": "Size Token"
    },
    {
      "name": "Border-width-S",
      "value": 1.5,
      "category": "Size Token"
    },
    {
      "name": "Border-width-M",
      "value": 1.75,
      "category": "Size Token"
    },
    {
      "name": "Border-width-L",
      "value": 2,
      "category": "Size Token"
    }
  ],
  "opacity": [
    {
      "name": "Frame",
      "opacity": 1,
      "category": "componets / Inputs & Controls",
      "rotation": 90
    },
    {
      "name": "Rectangle-20",
      "opacity": 0.7,
      "category": "componets / Menu / Property 1=Home / navigation/menu - left"
    },
    {
      "name": "Line-1",
      "opacity": 1,
      "category": "componets / Search Bar / Property 1=Search Bar - Back",
      "rotation": -90
    },
    {
      "name": "email-icon",
      "opacity": 1,
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / e icon+e text",
      "rotation": 0
    },
    {
      "name": "copy-2",
      "opacity": 1,
      "category": "Menu/Action Item - Single / inside menu highlight master / all tabs / e icon+e text / email icon",
      "rotation": 180
    },
    {
      "name": "Rectangle-10-state-Default-icon-false",
      "opacity": 0.25,
      "category": "New buttons / Primary button / state=Default, icon=false",
      "rotation": 68.42
    },
    {
      "name": "Rectangle-10-New-Recording-Variant2",
      "opacity": 0.2,
      "category": "componets / Button CTA / New Recording=Variant2",
      "rotation": 67.92
    },
    {
      "name": "Rectangle-9-state-Default-icon-false",
      "opacity": 0.2,
      "category": "New buttons / Primary button / state=Default, icon=false",
      "rotation": 68.42
    },
    {
      "name": "Rectangle-9-New-Recording-Variant2",
      "opacity": 0.1,
      "category": "componets / Button CTA / New Recording=Variant2",
      "rotation": 67.92
    },
    {
      "name": "Rectangle-11-state-Default-icon-false",
      "opacity": 0.4,
      "category": "New buttons / Primary button / state=Default, icon=false",
      "rotation": 14.23
    },
    {
      "name": "Rectangle-11-New-Recording-Variant2",
      "opacity": 0.4,
      "category": "componets / Button CTA / New Recording=Variant2",
      "rotation": 13.89
    },
    {
      "name": "Primary",
      "opacity": 0.06,
      "category": "New buttons / Secondary button / state=Default, icon=false",
      "rotation": 14.23
    }
  ],
  "gradients": [
    {
      "name": "Vector",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0,
          "color": "#34AD9E",
          "opacity": 1
        },
        {
          "position": 0.04,
          "color": "#22B7B8",
          "opacity": 1
        },
        {
          "position": 0.12,
          "color": "#09C6DE",
          "opacity": 1
        },
        {
          "position": 0.16,
          "color": "#00CCED",
          "opacity": 1
        },
        {
          "position": 0.37,
          "color": "#04C6E9",
          "opacity": 1
        },
        {
          "position": 0.63,
          "color": "#11B8E0",
          "opacity": 1
        },
        {
          "position": 0.9,
          "color": "#27A0D1",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#3096CB",
          "opacity": 1
        }
      ],
      "category": "componets / Navigation Bar / Property 1=New / Group / Clip path group"
    },
    {
      "name": "Rectangle-19",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0.317,
          "color": "#051321",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#051321",
          "opacity": 0
        }
      ],
      "category": "componets / Menu / Property 1=Home"
    },
    {
      "name": "Primary-button",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0,
          "color": "#3A3E7B",
          "opacity": 1
        },
        {
          "position": 0.565,
          "color": "#614AB0",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#9B5DFF",
          "opacity": 1
        }
      ],
      "category": "New buttons"
    },
    {
      "name": "white-white",
      "gradientType": "radial",
      "stops": [
        {
          "position": 0,
          "color": "#3074F3",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#002152",
          "opacity": 1
        }
      ],
      "category": "componets / Button CTA / New Recording=Variant2"
    },
    {
      "name": "Rectangle-9",
      "gradientType": "radial",
      "stops": [
        {
          "position": 0,
          "color": "#150B46",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#8E65EB",
          "opacity": 1
        }
      ],
      "category": "componets / Button CTA / New Recording=Variant2"
    },
    {
      "name": "Ellipse-3569",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0,
          "color": "#A268FF",
          "opacity": 0.8
        },
        {
          "position": 1,
          "color": "#3E95D6",
          "opacity": 1
        }
      ],
      "category": "componets / Meeting list - Item / Property 1=Default"
    },
    {
      "name": "Frame-1973342108",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0,
          "color": "#9B5DFF",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#30335D",
          "opacity": 1
        }
      ],
      "category": "componets / Popup"
    },
    {
      "name": "Primary",
      "gradientType": "linear",
      "stops": [
        {
          "position": 0,
          "color": "#6E3EBB",
          "opacity": 1
        },
        {
          "position": 1,
          "color": "#30335D",
          "opacity": 1
        }
      ],
      "category": "componets / Popup"
    }
  ],
  "blurs": [
    {
      "name": "Rectangle-20",
      "blurType": "layer",
      "radius": 42.599998474121094,
      "category": "componets / Menu / Property 1=Home / navigation/menu - left"
    },
    {
      "name": "Ellipse-3569",
      "blurType": "layer",
      "radius": 69.80000305175781,
      "category": "componets / Meeting list - Item / Property 1=Default"
    }
  ],
  "structure": [
    {
      "id": "525:6813",
      "type": "SECTION",
      "width": 2476,
      "height": 1148,
      "x": -412,
      "y": -319,
      "name": "componets",
      "fills": [
        {
          "type": "SOLID",
          "color": "#051321"
        }
      ],
      "children": [
        {
          "id": "524:12621",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "530:6998",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "VERTICAL",
          "paddingLeft": 12,
          "paddingRight": 12,
          "paddingTop": 12,
          "paddingBottom": 12,
          "itemSpacing": 14,
          "layoutSizingHorizontal": "HUG",
          "layoutSizingVertical": "HUG",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "530:7142",
          "type": "COMPONENT",
          "width": 73,
          "height": 40,
          "x": 139,
          "y": 679,
          "name": "Icon + Text",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "primaryAxisAlignItems": "CENTER",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 8,
          "paddingRight": 8,
          "paddingTop": 8,
          "paddingBottom": 8,
          "itemSpacing": 4,
          "layoutSizingHorizontal": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1B293A"
            }
          ],
          "strokes": [
            {
              "type": "SOLID",
              "color": "#2A4051",
              "weight": 1
            }
          ],
          "cornerRadius": 1400,
          "componentId": "530:7142",
          "children": [
            {
              "id": "530:7123",
              "type": "FRAME",
              "blendMode": "PASS_THROUGH",
              "fills": [
                {
                  "type": "SOLID",
                  "color": "#FFFFFF"
                }
              ]
            },
            {
              "id": "530:7106",
              "type": "TEXT",
              "blendMode": "PASS_THROUGH",
              "rotation": 0,
              "layoutSizingHorizontal": "HUG",
              "layoutSizingVertical": "HUG",
              "fills": [
                {
                  "type": "SOLID",
                  "color": "#FFFFFF"
                }
              ],
              "characters": "join",
              "fontSize": 14,
              "fontFamily": "Inter",
              "fontWeight": 500
            }
          ]
        },
        {
          "id": "530:11504",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "530:11998",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "530:12250",
          "type": "COMPONENT",
          "width": 69,
          "height": 20,
          "x": 460,
          "y": 195,
          "name": "Inputs & Controls",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "counterAxisAlignItems": "CENTER",
          "itemSpacing": 4,
          "layoutSizingHorizontal": "HUG",
          "layoutSizingVertical": "HUG",
          "componentId": "530:12250",
          "children": [
            {
              "id": "530:12205",
              "type": "TEXT",
              "blendMode": "PASS_THROUGH",
              "layoutSizingHorizontal": "HUG",
              "layoutSizingVertical": "HUG",
              "fills": [
                {
                  "type": "SOLID",
                  "color": "#FFFFFF"
                }
              ],
              "characters": "View all",
              "fontSize": 12,
              "fontFamily": "Inter",
              "fontWeight": 400
            },
            {
              "id": "530:12237",
              "type": "FRAME",
              "blendMode": "PASS_THROUGH",
              "rotation": 90,
              "fills": [
                {
                  "type": "SOLID",
                  "color": "#FFFFFF"
                }
              ]
            }
          ]
        },
        {
          "id": "530:12268",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "542:7439",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "VERTICAL",
          "paddingLeft": 8,
          "paddingRight": 8,
          "paddingTop": 8,
          "paddingBottom": 8,
          "itemSpacing": 8,
          "layoutSizingVertical": "HUG",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "542:7585",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        },
        {
          "id": "542:8919",
          "type": "COMPONENT_SET",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "VERTICAL",
          "paddingLeft": 24,
          "paddingRight": 24,
          "paddingTop": 24,
          "paddingBottom": 24,
          "itemSpacing": 8,
          "layoutSizingHorizontal": "HUG",
          "layoutSizingVertical": "HUG",
          "strokes": [
            {
              "type": "SOLID",
              "color": "#8A38F5",
              "weight": 1
            }
          ],
          "cornerRadius": 5
        }
      ]
    },
    {
      "id": "579:9475",
      "type": "INSTANCE",
      "width": 140,
      "height": 258,
      "x": 2106,
      "y": -223,
      "name": "Menu/Action Item - Single",
      "blendMode": "PASS_THROUGH",
      "layoutMode": "VERTICAL",
      "primaryAxisAlignItems": "CENTER",
      "counterAxisAlignItems": "CENTER",
      "layoutSizingHorizontal": "HUG",
      "layoutSizingVertical": "HUG",
      "mainComponentId": "579:8755",
      "children": [
        {
          "id": "I579:9475;18362:213007",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "VERTICAL",
          "primaryAxisAlignItems": "CENTER",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 10,
          "paddingRight": 10,
          "paddingTop": 10,
          "paddingBottom": 10,
          "itemSpacing": 8,
          "layoutSizingHorizontal": "HUG",
          "layoutSizingVertical": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#EFEFEF"
            }
          ],
          "cornerRadius": 8
        }
      ]
    },
    {
      "id": "579:9564",
      "type": "FRAME",
      "width": 335,
      "height": 320,
      "x": 2095,
      "y": 134,
      "name": "Frame 2147225523",
      "blendMode": "PASS_THROUGH",
      "layoutMode": "VERTICAL",
      "itemSpacing": 10,
      "layoutSizingVertical": "HUG",
      "children": [
        {
          "id": "579:9565",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 16,
          "paddingRight": 16,
          "paddingTop": 16,
          "paddingBottom": 16,
          "itemSpacing": 12,
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#8B4ED6",
              "opacity": 0.2
            }
          ],
          "strokes": [
            {
              "type": "SOLID",
              "color": "#2A4051",
              "weight": 1
            }
          ],
          "cornerRadius": 12
        },
        {
          "id": "579:9568",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 16,
          "paddingRight": 16,
          "paddingTop": 16,
          "paddingBottom": 16,
          "itemSpacing": 12,
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1B293A"
            }
          ],
          "strokes": [
            {
              "type": "SOLID",
              "color": "#2A4051",
              "weight": 1
            }
          ],
          "cornerRadius": 12
        },
        {
          "id": "579:9571",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 16,
          "paddingRight": 16,
          "paddingTop": 16,
          "paddingBottom": 16,
          "itemSpacing": 12,
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1B293A"
            }
          ],
          "strokes": [
            {
              "type": "SOLID",
              "color": "#2A4051",
              "weight": 1
            }
          ],
          "cornerRadius": 12
        },
        {
          "id": "579:9574",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 16,
          "paddingRight": 16,
          "paddingTop": 16,
          "paddingBottom": 16,
          "itemSpacing": 12,
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1B293A"
            }
          ],
          "strokes": [
            {
              "type": "SOLID",
              "color": "#2A4051",
              "weight": 1
            }
          ],
          "cornerRadius": 12
        },
        {
          "id": "579:9578",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "layoutMode": "HORIZONTAL",
          "counterAxisAlignItems": "CENTER",
          "paddingLeft": 16,
          "paddingRight": 16,
          "paddingTop": 16,
          "paddingBottom": 16,
          "itemSpacing": 12,
          "layoutSizingHorizontal": "FILL",
          "layoutSizingVertical": "HUG",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1B293A"
            }
          ],
          "strokes": [
            {
              "type": "SOLID",
              "color": "#2A4051",
              "weight": 1
            }
          ],
          "cornerRadius": 12
        }
      ]
    },
    {
      "id": "54628:8312",
      "type": "FRAME",
      "width": 618,
      "height": 805,
      "x": -412,
      "y": 1323,
      "name": "Buttons",
      "blendMode": "PASS_THROUGH",
      "layoutMode": "HORIZONTAL",
      "counterAxisAlignItems": "CENTER",
      "layoutSizingHorizontal": "HUG",
      "children": [
        {
          "id": "54628:8313",
          "type": "FRAME",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#F6F6F9"
            }
          ]
        }
      ]
    },
    {
      "id": "54628:8321",
      "type": "FRAME",
      "width": 1450,
      "height": 806,
      "x": 206,
      "y": 1322,
      "name": "New buttons",
      "blendMode": "PASS_THROUGH",
      "fills": [
        {
          "type": "SOLID",
          "color": "#9A9A9A"
        }
      ],
      "children": [
        {
          "id": "54628:8322",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Default",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8323",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "default + icon",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8324",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Primary",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8325",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Secondary",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8326",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Text",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8327",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Light/Dark mode toggle",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8328",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "multi function button",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8329",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Multi function component",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8330",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Pressed",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8331",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#1D1D1D"
            }
          ],
          "characters": "Disabled",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        }
      ]
    },
    {
      "id": "54628:8456",
      "type": "FRAME",
      "width": 1450,
      "height": 806,
      "x": 1656,
      "y": 1323,
      "name": "New buttons",
      "blendMode": "PASS_THROUGH",
      "fills": [
        {
          "type": "SOLID",
          "color": "#232D42"
        }
      ],
      "children": [
        {
          "id": "54628:8457",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Default",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8458",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "default + icon",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8459",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Primary",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8460",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Secondary",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8461",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Text",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8462",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Light/Dark mode toggle",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8463",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "multi function button",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8464",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Multi function component",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8465",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Pressed",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        },
        {
          "id": "54628:8466",
          "type": "TEXT",
          "blendMode": "PASS_THROUGH",
          "fills": [
            {
              "type": "SOLID",
              "color": "#D7E3EC"
            }
          ],
          "characters": "Delete",
          "fontSize": 20,
          "fontFamily": "Inter",
          "fontWeight": 600
        }
      ]
    },
    {
      "id": "54639:10213",
      "type": "RECTANGLE",
      "width": 100,
      "height": 100,
      "x": 3518,
      "y": 1223,
      "name": "Rectangle 22",
      "blendMode": "PASS_THROUGH",
      "fills": [
        {
          "type": "SOLID",
          "color": "#D9D9D9"
        }
      ]
    }
  ]
} as any;

export const designTokens = {
  colors: {
    /** #295365 */
    bodyTextFrame2147225184Default: "#295365",
    /** #1D1D1D */
    bodyTextButtons: "#1D1D1D",
    /** #D7E3EC */
    icons: "#D7E3EC",
    /** #191836 */
    buttons: "#191836",
    /** #091C2A */
    greyPage1: "#091C2A",
    /** #051321 */
    greyPage2: "#051321",
    /** #505D6F */
    disabled: "#505D6F",
    /** #6C7683 */
    disabledText: "#6C7683",
    /** #232D42 */
    figmaSection: "#232D42",
    /** #EFEFEF */
    grey100: "#EFEFEF",
    /** #7C7C7C */
    grey500: "#7C7C7C",
    /** #656565 */
    grey600Text: "#656565",
    /** #8E8EA9 */
    headerIcons: "#8E8EA9",
    /** #8A5ADB */
    primary: "#8A5ADB",
    /** #9B5DFF */
    purplePurple: "#9B5DFF",
    /** #EF355D */
    redError: "#EF355D",
    /** #F0F0F0 */
    selectedSecondaryButton: "#F0F0F0",
    /** #192557 */
    selectedMenuList: "#192557",
    /** #44DB95 */
    tagGreen44DB95: "#44DB95",
    /** #2B344D */
    textField: "#2B344D",
    /** #FFFFFF */
    whiteWhite: "#FFFFFF",
    /** #3074F3 */
    blueBlue: "#3074F3",
    /** #25A96B */
    greenGreen: "#25A96B",
    /** #1B293A */
    greyButtonsBg: "#1B293A",
    /** #ADB4CA */
    greyDrawerHandle: "#ADB4CA",
    /** #C9CFDC */
    greyGrey: "#C9CFDC",
    /** #90A3B1 */
    greySecondaryBodyText: "#90A3B1",
    /** #2A4051 */
    greyStroke: "#2A4051",
    /** #2F3649 */
    greyTextField: "#2F3649",
    /** #FFA000 */
    orangeOrangeWarning: "#FFA000",
    /** #C84747 */
    redRedError: "#C84747",
    /** #FF4B4B */
    redRedWarning: "#FF4B4B",
    /** #00FFFF */
    turquoiseTurquoise: "#00FFFF",
  },
  typography: {
    primary: {
      fontFamily: "Inter",
      fontSize: 64,
      fontWeight: 600,
      lineHeight: "normal",
    },
    bodyText: {
      fontFamily: "Inter",
      fontSize: 20,
      fontWeight: 500,
      lineHeight: 1.25,
    },
    whiteWhiteStatusBar: {
      fontFamily: "SF Pro",
      fontSize: 15,
      fontWeight: 600,
      lineHeight: "normal",
      letterSpacing: -0.17,
    },
    whiteWhiteContainer: {
      fontFamily: "SF Pro Text",
      fontSize: 17,
      fontWeight: 400,
      lineHeight: "normal",
    },
    whiteWhiteContainer2: {
      fontFamily: "SF Pro Text",
      fontSize: 14,
      fontWeight: 400,
      lineHeight: "normal",
    },
    grey600Text: {
      fontFamily: "Segoe UI",
      fontSize: 12,
      fontWeight: 400,
      lineHeight: 13,
    },
    token16Reg: {
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 24,
    },
    greyTextIcons: {
      fontFamily: "Heebo",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    labelSml: {
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 400,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    lableSami12: {
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 600,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    inter20SemiBold: {
      fontFamily: "Inter",
      fontSize: 20,
      fontWeight: 600,
      lineHeight: 1.25,
    },
    buttonText: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 1.25,
      letterSpacing: 1,
    },
    labelLarge14Med: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    labelReg14Reg: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 400,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    headlineReg16Med: {
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 500,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    token14Regular: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 20,
    },
    headlineMed18Med: {
      fontFamily: "Inter",
      fontSize: 18,
      fontWeight: 500,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    headlineReg16Reg: {
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "normal",
      textTransform: "capitalize",
    },
    body: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.25,
    },
    bodyBold: {
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 1.25,
    },
  },
  radius: {
    radiusXXS: { topLeft: 2, topRight: 2, bottomRight: 2, bottomLeft: 2 },
    radiusXS: { topLeft: 4, topRight: 4, bottomRight: 4, bottomLeft: 4 },
    radiusS: { topLeft: 8, topRight: 8, bottomRight: 8, bottomLeft: 8 },
    radiusM: { topLeft: 12, topRight: 12, bottomRight: 12, bottomLeft: 12 },
    radiusL: { topLeft: 16, topRight: 16, bottomRight: 16, bottomLeft: 16 },
    radiusXL: { topLeft: 20, topRight: 20, bottomRight: 20, bottomLeft: 20 },
    radiusFull: { topLeft: 99, topRight: 99, bottomRight: 99, bottomLeft: 99 },
    menu: { topLeft: 5, topRight: 5, bottomRight: 5, bottomLeft: 5 },
    icons: { topLeft: 1133.3333740234375, topRight: 1133.3333740234375, bottomRight: 1133.3333740234375, bottomLeft: 1133.3333740234375 },
    rectangle20: { topLeft: 10, topRight: 10, bottomRight: 10, bottomLeft: 10 },
    iconDone: { topLeft: 30, topRight: 30, bottomRight: 30, bottomLeft: 30 },
    primary: { topLeft: 156.69219970703125, topRight: 156.69219970703125, bottomRight: 156.69219970703125, bottomLeft: 156.69219970703125 },
    rectangle: { topLeft: 1.2000000476837158, topRight: 1.2000000476837158, bottomRight: 1.2000000476837158, bottomLeft: 1.2000000476837158 },
    greyButtonsBg: { topLeft: 1400, topRight: 1400, bottomRight: 1400, bottomLeft: 1400 },
    rectangle9: { topLeft: 200, topRight: 200, bottomRight: 200, bottomLeft: 200 },
    greyPage: { topLeft: 24, topRight: 24, bottomRight: 24, bottomLeft: 24 },
    frame1973342108: { topLeft: 44.4444465637207, topRight: 44.4444465637207, bottomRight: 44.4444465637207, bottomLeft: 44.4444465637207 },
    tertiary: { topLeft: 58, topRight: 58, bottomRight: 58, bottomLeft: 58 },
  },
  shadows: {
    vector: [{"type":"drop","color":"#000000","opacity":0.25,"offsetX":0,"offsetY":4,"blur":4,"spread":0}],
    designSystemButtonShadow: [{"type":"drop","color":"#160532","opacity":0.2,"offsetX":0,"offsetY":1.5,"blur":3,"spread":0}],
  },
  borders: {
    greyPageMeetingListItem: { color: "#2A4051", weight: 1, strokeAlign: "INSIDE" },
    greyPageProperty1Home: { color: "#2A4051", weight: 1, strokeAlign: "OUTSIDE" },
    menu: { color: "#8A38F5", weight: 1, strokeAlign: "INSIDE" },
    vectorIcons: { color: "#90A3B1", weight: 1.5, strokeAlign: "CENTER" },
    vectorFrame: { color: "#FFFFFF", weight: 1.25, strokeAlign: "CENTER" },
    vectorNavigation: { color: "#FFFFFF", weight: 1.5833332538604736, strokeAlign: "CENTER" },
    vectorNavigation2: { color: "#FFFFFF", weight: 1.5, strokeAlign: "INSIDE" },
    vectorFrame2: { color: "#FFFFFF", weight: 1, strokeAlign: "CENTER" },
    vectorFrame3: { color: "#D7E3EC", weight: 1.5, strokeAlign: "CENTER" },
    vectorFrame4: { color: "#D7E3EC", weight: 1.25, strokeAlign: "CENTER" },
    vectorFrame5: { color: "#FFFFFF", weight: 1.5, strokeAlign: "CENTER" },
    vectorFrame6: { color: "#C84747", weight: 1, strokeAlign: "CENTER" },
    vectorFrame7: { color: "#FFFFFF", weight: 1.0416666269302368, strokeAlign: "CENTER" },
    vectorFrame8: { color: "#D7E3EC", weight: 1.0416666269302368, strokeAlign: "CENTER" },
    vectorFrame9: { color: "#FF4B4B", weight: 1.25, strokeAlign: "CENTER" },
    vectorAiSearch02: { color: "#D7E3EC", weight: 1.125, strokeAlign: "CENTER" },
    iconDone: { color: "#7C7C7C", weight: 2, strokeAlign: "INSIDE" },
    line10: { color: "#525C6D", weight: 1, strokeAlign: "CENTER" },
    confirm: { color: "#9B5DFF", weight: 1, strokeAlign: "INSIDE" },
    greyButtonsBg: { color: "#2A4051", weight: 1.1333333253860474, strokeAlign: "INSIDE" },
    line1: { color: "#90A3B1", weight: 1, strokeAlign: "CENTER" },
    grey500Done: { color: "#7C7C7C", weight: 2, strokeAlign: "CENTER" },
    grey500Group: { color: "#7C7C7C", weight: 0.5, strokeAlign: "CENTER" },
    white: { color: "#000000", weight: 1, strokeAlign: "INSIDE" },
    vector1: { color: "#D7E3EC", weight: 2, strokeAlign: "CENTER" },
    disabled: { color: "#505D6F", weight: 1, strokeAlign: "INSIDE" },
    greyTextIconsFrame: { color: "#D7E3EC", weight: 1.1773462295532227, strokeAlign: "INSIDE" },
    greyTextIconsFrame2: { color: "#FFFFFF", weight: 1.1852092742919922, strokeAlign: "INSIDE" },
    greyTextIconsAiSearch02: { color: "#D7E3EC", weight: 0.7499999403953552, strokeAlign: "CENTER" },
  },
  opacity: {
    frame: 1,
    rectangle20: 0.7,
    line1: 1,
    emailIcon: 1,
    copy2: 1,
    rectangle10StateDefaultIconFalse: 0.25,
    rectangle10NewRecordingVariant2: 0.2,
    rectangle9StateDefaultIconFalse: 0.2,
    rectangle9NewRecordingVariant2: 0.1,
    rectangle11StateDefaultIconFalse: 0.4,
    rectangle11NewRecordingVariant2: 0.4,
    primary: 0.06,
  },
  gradients: {
    vector: {"type":"linear","stops":[{"position":0,"color":"#34AD9E","opacity":1},{"position":0.04,"color":"#22B7B8","opacity":1},{"position":0.12,"color":"#09C6DE","opacity":1},{"position":0.16,"color":"#00CCED","opacity":1},{"position":0.37,"color":"#04C6E9","opacity":1},{"position":0.63,"color":"#11B8E0","opacity":1},{"position":0.9,"color":"#27A0D1","opacity":1},{"position":1,"color":"#3096CB","opacity":1}]},
    rectangle19: {"type":"linear","stops":[{"position":0.317,"color":"#051321","opacity":1},{"position":1,"color":"#051321","opacity":0}]},
    primaryButton: {"type":"linear","stops":[{"position":0,"color":"#3A3E7B","opacity":1},{"position":0.565,"color":"#614AB0","opacity":1},{"position":1,"color":"#9B5DFF","opacity":1}]},
    whiteWhite: {"type":"radial","stops":[{"position":0,"color":"#3074F3","opacity":1},{"position":1,"color":"#002152","opacity":1}]},
    rectangle9: {"type":"radial","stops":[{"position":0,"color":"#150B46","opacity":1},{"position":1,"color":"#8E65EB","opacity":1}]},
    ellipse3569: {"type":"linear","stops":[{"position":0,"color":"#A268FF","opacity":0.8},{"position":1,"color":"#3E95D6","opacity":1}]},
    frame1973342108: {"type":"linear","stops":[{"position":0,"color":"#9B5DFF","opacity":1},{"position":1,"color":"#30335D","opacity":1}]},
    primary: {"type":"linear","stops":[{"position":0,"color":"#6E3EBB","opacity":1},{"position":1,"color":"#30335D","opacity":1}]},
  },
  blurs: {
    rectangle20: { type: "layer", radius: 42.599998474121094 },
    ellipse3569: { type: "layer", radius: 69.80000305175781 },
  },
  elevations: {
    elevation8: [{"type":"drop","color":"#000000","opacity":0.2,"offsetX":0,"offsetY":5,"blur":5,"spread":-3},{"type":"drop","color":"#000000","opacity":0.14,"offsetX":0,"offsetY":8,"blur":10,"spread":1},{"type":"drop","color":"#000000","opacity":0.12,"offsetX":0,"offsetY":3,"blur":14,"spread":2}],
  },
  sizes: {
    spaceXXS: 4,
    spaceXS: 8,
    spaceS: 12,
    spaceM: 16,
    spaceL: 20,
    spaceXL: 24,
    spaceXXL: 32,
    spaceXXXL: 40,
    borderWidthXXS: 1,
    borderWidthXS: 1.25,
    borderWidthS: 1.5,
    borderWidthM: 1.75,
    borderWidthL: 2,
  },
} as const;

export type DesignTokens = typeof designTokens;
export type ColorKey = keyof typeof designTokens.colors;
export type TypographyKey = keyof typeof designTokens.typography;
