/* Auto-generated by Guing — hex values resolved at publish time. Do not edit manually. */

/**
 * Semantic color hex values derived directly from the Figma token set.
 * Import this in theme.ts instead of resolving at runtime from tokens.json.
 */
export const themeSemantics = {
  brand100: "#e0f2fe",
  brand300: "#7dd3fc",
  brand500: "#0ea5e9",
  brand700: "#0369a1",
  actionPrimary: "#0ea5e9",
  actionSecondary: "#6b7280",
  success500: "#22c55e",
  warning500: "#f59e0b",
  danger500: "#ef4444",
  surface: "#ffffff",
  background: "#f8fafc",
  textMain: "#111827",
  textMuted: "#6b7280",
  white: "#ffffff",
  black: "#000000",
  neutral300: "#d1d5db",
  borderDivider: "#e5e7eb",
} as const;
