/* Auto-generated by Guing — hex values resolved at publish time. Do not edit manually. */

/**
 * Semantic color hex values derived directly from the Figma token set.
 * Import this in theme.ts instead of resolving at runtime from tokens.json.
 */
export const themeSemantics = {
  brand100: "#E0EAFD",
  brand300: "#83ACF8",
  brand500: "#3074F3",
  brand700: "#2457B6",
  actionPrimary: "#3074F3",
  actionSecondary: "#9B5DFF",
  success500: "#25A96B",
  warning500: "#FFA000",
  danger500: "#C84747",
  surface: "#091C2A",
  background: "#051321",
  textMain: "#D7E3EC",
  textMuted: "#90A3B1",
  white: "#FFFFFF",
  black: "#000000",
  neutral300: "#D1D5DB",
  borderDivider: "#2A4051",
} as const;
