/* Auto-generated by Guing — hex values resolved at publish time. Do not edit manually. */

/**
 * Semantic color hex values derived directly from the Figma token set.
 * Import this in theme.ts instead of resolving at runtime from tokens.json.
 */
export const themeSemantics = {
  brand100: "#E4EFFB",
  brand300: "#93C0F1",
  brand500: "#4B96E7",
  brand700: "#3871AD",
  actionPrimary: "#4B96E7",
  actionSecondary: "#6b7280",
  success500: "#03834A",
  warning500: "#B45803",
  danger500: "#BB251A",
  surface: "#FFFFFF",
  background: "#FFFFFF",
  textMain: "#1D1F23",
  textMuted: "#8B939F",
  white: "#FFFFFF",
  black: "#000000",
  neutral300: "#D1D5DB",
  borderDivider: "#E4E7EC",
} as const;
