/* Auto-generated by Guing — do not edit manually */

export interface ColorToken {
  name: string;
  value: string;
  category?: string;
}

export interface GradientStop {
  position: number;
  color: string;
  opacity: number;
}

export interface GradientToken {
  name: string;
  gradientType: string;
  stops: GradientStop[];
  category?: string;
}

export interface TypographyToken {
  name: string;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  lineHeight: number | string;
  letterSpacing?: number;
  textTransform?: string;
  color?: string;
  category?: string;
}

export interface RadiusToken {
  name: string;
  value: number;
  topLeft: number;
  topRight: number;
  bottomRight: number;
  bottomLeft: number;
  category?: string;
}

export interface ShadowEffect {
  type: "drop" | "inner";
  color: string;
  opacity: number;
  offsetX: number;
  offsetY: number;
  blur: number;
  spread: number;
}

export interface ShadowToken {
  name: string;
  shadows: ShadowEffect[];
  category?: string;
}

export interface BorderToken {
  name: string;
  color: string;
  weight: number;
  strokeAlign: string;
  dashPattern?: number[];
  strokeCap?: string;
  strokeJoin?: string;
  strokeMiterLimit?: number;
  strokeTopWeight?: number;
  strokeRightWeight?: number;
  strokeBottomWeight?: number;
  strokeLeftWeight?: number;
  category?: string;
}

export interface ElevationToken {
  name: string;
  shadows: ShadowEffect[];
  category?: string;
}

export interface GapToken {
  name: string;
  value: number;
  category?: string;
}

export interface SizeToken {
  name: string;
  value: number;
  category?: string;
}

export interface OpacityToken {
  name: string;
  opacity: number;
  blendMode?: string;
  rotation?: number;
  category?: string;
}

export interface BlurToken {
  name: string;
  blurType: "layer" | "background";
  radius: number;
  category?: string;
}

export interface LayoutGridToken {
  name: string;
  grids: Array<{
    pattern: string;
    sectionSize?: number;
    gutterSize?: number;
    count?: number;
    alignment?: string;
  }>;
  category?: string;
}

export interface IconToken {
  name: string;
  svg: string;
  category?: string;
}

export interface DesignTokens {
  colors: ColorToken[];
  gradients?: GradientToken[];
  typography: TypographyToken[];
  radius?: RadiusToken[];
  shadows?: ShadowToken[];
  elevations?: ElevationToken[];
  borders?: BorderToken[];
  gaps?: GapToken[];
  sizes?: SizeToken[];
  opacity?: OpacityToken[];
  blurs?: BlurToken[];
  layoutGrids?: LayoutGridToken[];
  icons?: IconToken[];
}
