/* Auto-generated by Guing — do not edit manually */

import { PrimayButton } from '../PrimayButton/PrimayButton';

export const PrimayButton = {
  PrimayButton: PrimayButton,
};

export { PrimayButton };
