// @guing:generated-baseline hash:437f9780ffbf
// Do not edit this file — it is used by guing for 3-way merge on re-sync
import React from 'react';
import { MuiMenu, MuiMenuItem, MuiDivider, MuiTypography, MuiBox } from '../adapters/mui/internal';

export interface MenuItemConfig {
  id: string;
  label: string;
  icon?: React.ReactNode;
  disabled?: boolean;
  destructive?: boolean;
  showDividerAfter?: boolean;
}

export interface MenuProps {
  /** Anchor element for MuiMenu positioning */
  anchorEl?: HTMLElement | null;
  /** Whether the menu is open */
  open?: boolean;
  /** Items to display */
  items?: MenuItemConfig[];
  /** Accessible label for the menu */
  label?: string;
  /** Leading icon slot */
  icon?: React.ReactNode;
  /** Disable all items */
  disabled?: boolean;
  /** Show divider between groups */
  showDivider?: boolean;
  /** Mark as destructive variant */
  destructive?: boolean;
  /** Variant */
  variant?: 'default' | 'destructive' | 'disabled' | 'withIcon' | 'withDivider';
  onItemClick?: (id: string) => void;
  onClose?: () => void;
  onSelect?: (id: string) => void;
  onClick?: () => void;
  onHover?: () => void;
  isDisabled?: boolean;
  isLoading?: boolean;
  children?: React.ReactNode;
  sx?: object;
  className?: string;
}

const DoneIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="10" cy="10" r="8.5" stroke="#90A3B1" strokeWidth="1.5" fill="none" />
    <path d="M6.5 10L8.75 12.25L13.5 7.5" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const PlannerIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="2" y="2" width="16" height="16" rx="2" fill="#1B7F47" />
    <rect x="5" y="5" width="4" height="4" rx="0.5" fill="white" />
    <rect x="11" y="5" width="4" height="4" rx="0.5" fill="white" />
    <rect x="5" y="11" width="4" height="4" rx="0.5" fill="white" />
    <rect x="11" y="11" width="4" height="4" rx="0.5" fill="white" />
  </svg>
);

const MondayIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <ellipse cx="5" cy="13" rx="3" ry="3" fill="#FF3D57" />
    <ellipse cx="10" cy="13" rx="3" ry="3" fill="#FFCB00" />
    <ellipse cx="15" cy="13" rx="3" ry="3" fill="#00CA72" />
  </svg>
);

const ZohoIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="10" cy="10" r="8" fill="white" />
    <path d="M5 10C5 7.23858 7.23858 5 10 5C11.6569 5 13.1569 5.83579 14.0711 7.12132" stroke="#E42527" strokeWidth="1.5" strokeLinecap="round" />
    <path d="M15 10C15 12.7614 12.7614 15 10 15C8.34315 15 6.84315 14.1642 5.92893 12.8787" stroke="#006DB6" strokeWidth="1.5" strokeLinecap="round" />
    <circle cx="10" cy="10" r="2" fill="#F5A623" />
  </svg>
);

const EditIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M13.5 3.5L16.5 6.5L7.5 15.5H4.5V12.5L13.5 3.5Z" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const CopyIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="7" y="7" width="9" height="9" rx="1.5" stroke="#90A3B1" strokeWidth="1.5" />
    <path d="M13 7V5.5C13 4.67157 12.3284 4 11.5 4H5.5C4.67157 4 4 4.67157 4 5.5V11.5C4 12.3284 4.67157 13 5.5 13H7" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const DeleteIcon = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M4 6H16" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
    <path d="M8 6V4H12V6" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    <rect x="5.5" y="6" width="9" height="10" rx="1" stroke="#90A3B1" strokeWidth="1.5" />
    <path d="M8 9V13" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
    <path d="M12 9V13" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const DEFAULT_ITEMS: MenuItemConfig[] = [
  { id: 'done', label: 'Done', icon: <DoneIcon /> },
  { id: 'send-to-planner', label: 'Send to Planner', icon: <PlannerIcon /> },
  { id: 'send-to-monday', label: 'Send to Monday', icon: <MondayIcon />, showDividerAfter: false },
  { id: 'send-to-zoho', label: 'Send to Zoho', icon: <ZohoIcon />, showDividerAfter: true },
  { id: 'edit', label: 'Edit', icon: <EditIcon /> },
  { id: 'copy', label: 'Copy', icon: <CopyIcon /> },
  { id: 'delete', label: 'Delete', icon: <DeleteIcon />, destructive: false },
];

const Menu = React.forwardRef<HTMLDivElement, MenuProps>((
  {
    anchorEl,
    open = true,
    items = DEFAULT_ITEMS,
    label = 'Action Menu',
    icon,
    disabled = false,
    showDivider = true,
    destructive = false,
    variant = 'default',
    onItemClick,
    onClose,
    onSelect,
    onClick,
    onHover,
    isDisabled = false,
    isLoading = false,
    children,
    sx = {},
    className,
  },
  ref
) => {
  const isAllDisabled = disabled || isDisabled || variant === 'disabled';
  const isDestructive = destructive || variant === 'destructive';
  const hasShowDivider = showDivider || variant === 'withDivider';

  const handleItemClick = (id: string) => {
    if (isAllDisabled) return;
    onItemClick?.(id);
    onSelect?.(id);
    onClick?.();
  };

  const renderItems = () => {
    const elements: React.ReactNode[] = [];

    items.forEach((item, index) => {
      const isItemDisabled = isAllDisabled || item.disabled;
      const isItemDestructive = (isDestructive && item.id === 'delete') || item.destructive;

      elements.push(
        <MuiMenuItem
          key={item.id}
          disabled={isItemDisabled}
          onClick={() => handleItemClick(item.id)}
          sx={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: '12px',
            px: '16px',
            py: '8px',
            minHeight: '36px',
            backgroundColor: 'transparent',
            color: isItemDestructive
              ? 'var(--color-danger-500, #C84747)'
              : 'var(--color-text-main, #D7E3EC)',
            fontFamily: 'var(--font-body-regular-family, Inter)',
            fontSize: 'var(--font-body-regular-size, 14px)',
            fontWeight: 'var(--font-body-regular-weight, 400)',
            lineHeight: '1.25',
            transition: 'background-color 0.15s ease',
            '&:hover': {
              backgroundColor: 'rgba(255, 255, 255, 0.06)',
            },
            '&.Mui-disabled': {
              opacity: 0.4,
              color: 'var(--color-text-muted, #90A3B1)',
            },
          }}
        >
          {item.icon && (
            <MuiBox
              sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '20px',
                height: '20px',
                flexShrink: 0,
              }}
            >
              {item.icon}
            </MuiBox>
          )}
          <MuiTypography
            sx={{
              fontFamily: 'var(--font-body-regular-family, Inter)',
              fontSize: 'var(--font-body-regular-size, 14px)',
              fontWeight: 'var(--font-body-regular-weight, 400)',
              lineHeight: '1.25',
              color: 'inherit',
            }}
          >
            {item.label}
          </MuiTypography>
        </MuiMenuItem>
      );

      if (hasShowDivider && item.showDividerAfter) {
        elements.push(
          <MuiDivider
            key={`divider-${index}`}
            sx={{
              borderColor: 'var(--color-border-divider, #2A4051)',
              borderWidth: '1px',
              my: '4px',
              mx: 0,
            }}
          />
        );
      }
    });

    return elements;
  };

  // Static render mode (no anchor): render as a standalone card
  if (!anchorEl) {
    return (
      <MuiBox
        ref={ref}
        data-figma-component="Menu"
        className={className}
        aria-label={label}
        sx={{
          width: '140px',
          minHeight: '258px',
          backgroundColor: 'var(--color-white, #FFFFFF)',
          borderRadius: '4px',
          boxShadow: '0px 4px 16px rgba(0,0,0,0.18)',
          display: 'flex',
          flexDirection: 'column',
          py: '8px',
          overflow: 'hidden',
          ...sx,
        }}
        onClick={onClick}
        onMouseEnter={onHover}
      >
        {renderItems()}
        {children}
      </MuiBox>
    );
  }

  return (
    <MuiBox
      ref={ref}
      data-figma-component="Menu"
      className={className}
      sx={{ display: 'contents', ...sx }}
    >
      <MuiMenu
        anchorEl={anchorEl}
        open={open}
        onClose={onClose}
        aria-label={label}
        sx={{
          '& .MuiPaper-root': {
            width: '140px',
            minHeight: '258px',
            backgroundColor: 'var(--color-white, #FFFFFF)',
            borderRadius: '4px',
            boxShadow: '0px 4px 16px rgba(0,0,0,0.18)',
            py: '8px',
          },
          '& .MuiList-root': {
            py: 0,
          },
        }}
      >
        {renderItems()}
        {children}
      </MuiMenu>
    </MuiBox>
  );
});

Menu.displayName = 'Menu';

export { Menu };
