// @guing:generated-baseline hash:437f9780ffbf
// Do not edit this file — it is used by guing for 3-way merge on re-sync
import React from 'react';
import { MuiMenu, MuiMenuItem, MuiDivider, MuiTypography, MuiBox } from '../adapters/mui/internal';

export interface MenuItemConfig {
  id: string;
  label: string;
  icon?: React.ReactNode;
  disabled?: boolean;
  destructive?: boolean;
  showDividerAfter?: boolean;
}

export type MenuVariant = 'default' | 'destructive' | 'disabled' | 'withIcon' | 'withDivider';

export interface MenuProps {
  items?: MenuItemConfig[];
  label?: string;
  icon?: React.ReactNode;
  disabled?: boolean;
  showDivider?: boolean;
  destructive?: boolean;
  variant?: MenuVariant;
  anchorEl?: HTMLElement | null;
  open?: boolean;
  onItemClick?: (item: MenuItemConfig) => void;
  onClose?: () => void;
  onSelect?: (item: MenuItemConfig) => void;
  onClick?: () => void;
  onHover?: () => void;
  isDisabled?: boolean;
  isLoading?: boolean;
  children?: React.ReactNode;
  sx?: Record<string, unknown>;
  className?: string;
}

const DoneIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="10" cy="10" r="8" stroke="#90A3B1" strokeWidth="1.5" fill="none" />
    <path d="M6.5 10.5L8.5 12.5L13.5 7.5" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const PlannerIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="2" y="2" width="16" height="16" rx="2" fill="#31752F" />
    <rect x="4" y="4" width="5" height="5" rx="0.5" fill="white" opacity="0.9" />
    <rect x="11" y="4" width="5" height="2" rx="0.5" fill="white" opacity="0.7" />
    <rect x="11" y="8" width="5" height="2" rx="0.5" fill="white" opacity="0.7" />
    <rect x="4" y="11" width="12" height="2" rx="0.5" fill="white" opacity="0.7" />
    <rect x="4" y="15" width="8" height="2" rx="0.5" fill="white" opacity="0.7" />
  </svg>
);

const MondayIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <ellipse cx="4.5" cy="13" rx="3" ry="3" fill="#FF3D57" />
    <ellipse cx="10" cy="13" rx="3" ry="3" fill="#FFCB00" />
    <ellipse cx="15.5" cy="13" rx="3" ry="3" fill="#00CA72" />
  </svg>
);

const ZohoIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="10" cy="10" r="8" fill="white" stroke="#E8E8E8" strokeWidth="0.5" />
    <path d="M10 3C10 3 14 5 14 10C14 15 10 17 10 17" stroke="#E61E25" strokeWidth="2" strokeLinecap="round" />
    <path d="M10 3C10 3 6 5 6 10C6 15 10 17 10 17" stroke="#00A650" strokeWidth="2" strokeLinecap="round" />
    <path d="M3 10H17" stroke="#0069AA" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const EditIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M14.5 2.5L17.5 5.5L7 16H4V13L14.5 2.5Z" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
    <path d="M12 5L15 8" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const CopyIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="7" y="7" width="10" height="10" rx="1.5" stroke="#90A3B1" strokeWidth="1.5" fill="none" />
    <path d="M5 13H4C3.45 13 3 12.55 3 12V4C3 3.45 3.45 3 4 3H12C12.55 3 13 3.45 13 4V5" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" fill="none" />
  </svg>
);

const DeleteIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M3 5H17" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
    <path d="M8 5V3H12V5" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
    <rect x="5" y="5" width="10" height="12" rx="1" stroke="#90A3B1" strokeWidth="1.5" fill="none" />
    <path d="M8 9V14" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
    <path d="M12 9V14" stroke="#90A3B1" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const DEFAULT_ITEMS: MenuItemConfig[] = [
  { id: 'done', label: 'Done', icon: <DoneIcon /> },
  { id: 'planner', label: 'Send to Planner', icon: <PlannerIcon /> },
  { id: 'monday', label: 'Send to Monday', icon: <MondayIcon /> },
  { id: 'zoho', label: 'Send to Zoho', icon: <ZohoIcon />, showDividerAfter: true },
  { id: 'edit', label: 'Edit', icon: <EditIcon /> },
  { id: 'copy', label: 'Copy', icon: <CopyIcon /> },
  { id: 'delete', label: 'Delete', icon: <DeleteIcon /> },
];

const Menu = React.forwardRef<HTMLDivElement, MenuProps>((
  {
    items = DEFAULT_ITEMS,
    label,
    icon,
    disabled = false,
    showDivider = true,
    destructive = false,
    variant = 'default',
    anchorEl,
    open = false,
    onItemClick,
    onClose,
    onSelect,
    onClick,
    onHover,
    isDisabled = false,
    isLoading = false,
    children,
    sx,
    className,
  },
  ref
) => {
  const isMenuDisabled = disabled || isDisabled || variant === 'disabled';

  const handleItemClick = (item: MenuItemConfig) => {
    if (item.disabled || isMenuDisabled) return;
    onItemClick?.(item);
    onSelect?.(item);
    onClose?.();
  };

  const menuItemSx = (item: MenuItemConfig) => ({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12px',
    px: '16px',
    py: '6px',
    minHeight: '36px',
    opacity: (item.disabled || isMenuDisabled) ? 0.4 : 1,
    color: item.destructive || (variant === 'destructive' && destructive)
      ? 'var(--color-danger-500, #C84747)'
      : 'var(--color-black, #000000)',
    fontFamily: 'var(--font-body-regular-family, Inter)',
    fontSize: 'var(--font-body-regular-size, 14px)',
    fontWeight: 'var(--font-body-regular-weight, 400)',
    backgroundColor: 'transparent',
    cursor: (item.disabled || isMenuDisabled) ? 'not-allowed' : 'pointer',
    '&:hover': {
      backgroundColor: 'rgba(0,0,0,0.06)',
    },
  });

  const dividerSx = {
    borderColor: 'rgba(0,0,0,0.15)',
    my: '4px',
    mx: 0,
  };

  const renderItems = (itemList: MenuItemConfig[]) => {
    const result: React.ReactNode[] = [];
    itemList.forEach((item, idx) => {
      result.push(
        <MuiMenuItem
          key={item.id}
          disabled={item.disabled || isMenuDisabled}
          onClick={() => handleItemClick(item)}
          sx={menuItemSx(item)}
        >
          {item.icon && (
            <MuiBox
              sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '20px',
                height: '20px',
                flexShrink: 0,
              }}
            >
              {item.icon}
            </MuiBox>
          )}
          <MuiTypography
            sx={{
              fontFamily: 'var(--font-body-regular-family, Inter)',
              fontSize: 'var(--font-body-regular-size, 14px)',
              fontWeight: 'var(--font-body-regular-weight, 400)',
              color: 'inherit',
              lineHeight: '1.25',
            }}
          >
            {item.label}
          </MuiTypography>
        </MuiMenuItem>
      );
      if (item.showDividerAfter) {
        result.push(<MuiDivider key={`divider-${idx}`} sx={dividerSx} />);
      }
    });
    return result;
  };

  // When used as a standalone/static panel (no anchor, no open)
  // OR always render the static panel as the root with data-figma-component
  // so the attribute is always findable in the DOM.
  return (
    <MuiBox
      ref={ref}
      data-figma-component="Menu"
      className={className}
      sx={{
        width: '140px',
        minHeight: '258px',
        backgroundColor: 'var(--color-white, #FFFFFF)',
        borderRadius: '8px',
        boxShadow: '0px 4px 16px 0px rgba(0,0,0,0.16)',
        display: 'flex',
        flexDirection: 'column',
        py: '8px',
        color: 'var(--color-black, #000000)',
        overflow: 'hidden',
        position: 'relative',
        ...sx,
      }}
      onClick={onClick}
      onMouseEnter={onHover}
    >
      {renderItems(items)}
      {children}
      {/* Portal-based MuiMenu rendered alongside for anchor-driven usage */}
      {anchorEl !== undefined && (
        <MuiMenu
          anchorEl={anchorEl}
          open={open}
          onClose={onClose}
          sx={{
            '& .MuiPaper-root': {
              width: '140px',
              minHeight: '258px',
              backgroundColor: 'var(--color-white, #FFFFFF)',
              borderRadius: '8px',
              boxShadow: '0px 4px 16px 0px rgba(0,0,0,0.16)',
              py: '8px',
              color: 'var(--color-black, #000000)',
            },
            '& .MuiList-root': {
              py: 0,
            },
          }}
        >
          {renderItems(items)}
          {children}
        </MuiMenu>
      )}
    </MuiBox>
  );
});

Menu.displayName = 'Menu';

export { Menu };
