// @guing:generated-baseline hash:5f2fd5ed4b08
// Do not edit this file — it is used by guing for 3-way merge on re-sync
import React from 'react';
import {
  MuiDialog,
  MuiDialogTitle,
  MuiDialogContent,
  MuiDialogActions,
  MuiBox,
  MuiTypography,
  MuiButton,
} from '../adapters/mui/internal';

export interface PopupProps {
  title?: string;
  message?: string;
  confirmLabel?: string;
  cancelLabel?: string;
  iconVariant?: 'notice' | 'warning' | 'danger' | 'info';
  visible?: boolean;
  variant?: 'notice' | 'warning' | 'danger' | 'info';
  onConfirm?: () => void;
  onCancel?: () => void;
  onClose?: () => void;
  onPrimary?: () => void;
  onClick?: () => void;
  onHover?: () => void;
  isDisabled?: boolean;
  isLoading?: boolean;
  children?: React.ReactNode;
  sx?: Record<string, unknown>;
  className?: string;
}

const WarningIcon = () => (
  <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="url(#paint0_linear_551_6542)"/>
    <path d="M28.6084 24.4999L21.9417 12.8332C21.7964 12.5767 21.5856 12.3634 21.3308 12.2149C21.0761 12.0665 20.7866 11.9883 20.4917 11.9883C20.1969 11.9883 19.9074 12.0665 19.6526 12.2149C19.3979 12.3634 19.1871 12.5767 19.0417 12.8332L12.3751 24.4999C12.2281 24.7543 12.1511 25.0431 12.1517 25.337C12.1524 25.6308 12.2307 25.9192 12.3788 26.173C12.5268 26.4269 12.7394 26.637 12.9948 26.7822C13.2503 26.9274 13.5396 27.0025 13.8334 26.9999H27.1667C27.4591 26.9996 27.7463 26.9223 27.9995 26.7759C28.2526 26.6295 28.4627 26.4191 28.6088 26.1658C28.7549 25.9125 28.8318 25.6252 28.8317 25.3328C28.8316 25.0404 28.7546 24.7531 28.6084 24.4999Z" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M20.5 17V20.3333" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M20.5 23.667H20.5083" stroke="white" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
    <defs>
      <linearGradient id="paint0_linear_551_6542" x1="30.5263" y1="2.17389e-06" x2="1.41551" y2="30.215" gradientUnits="userSpaceOnUse">
        <stop stopColor="#9B5DFF"/>
        <stop offset="1" stopColor="#30335D"/>
      </linearGradient>
    </defs>
  </svg>
);

const InfoIcon = () => (
  <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="url(#info_gradient)"/>
    <path d="M20 14C19.4477 14 19 14.4477 19 15C19 15.5523 19.4477 16 20 16C20.5523 16 21 15.5523 21 15C21 14.4477 20.5523 14 20 14Z" fill="white"/>
    <path d="M20 18V26" stroke="white" strokeWidth="1.5" strokeLinecap="round"/>
    <defs>
      <linearGradient id="info_gradient" x1="30.5263" y1="2.17389e-06" x2="1.41551" y2="30.215" gradientUnits="userSpaceOnUse">
        <stop stopColor="#3074F3"/>
        <stop offset="1" stopColor="#30335D"/>
      </linearGradient>
    </defs>
  </svg>
);

const DangerIcon = () => (
  <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="url(#danger_gradient)"/>
    <path d="M14 14L26 26M26 14L14 26" stroke="white" strokeWidth="1.5" strokeLinecap="round"/>
    <defs>
      <linearGradient id="danger_gradient" x1="30.5263" y1="2.17389e-06" x2="1.41551" y2="30.215" gradientUnits="userSpaceOnUse">
        <stop stopColor="#FF4B4B"/>
        <stop offset="1" stopColor="#30335D"/>
      </linearGradient>
    </defs>
  </svg>
);

const getIcon = (variant?: string) => {
  switch (variant) {
    case 'info': return <InfoIcon />;
    case 'danger': return <DangerIcon />;
    case 'warning': return <WarningIcon />;
    case 'notice':
    default: return <WarningIcon />;
  }
};

const getButtonGradient = (variant?: string): string => {
  switch (variant) {
    case 'danger': return 'linear-gradient(278deg, #C84747 0%, #30335D 100%)';
    case 'info': return 'linear-gradient(278deg, #3074F3 0%, #30335D 100%)';
    case 'warning': return 'linear-gradient(278deg, #FFA000 0%, #30335D 100%)';
    case 'notice':
    default: return 'linear-gradient(278deg, #6E3EBB 0%, #30335D 100%)';
  }
};

const Popup = React.forwardRef<HTMLDivElement, PopupProps>((
  {
    title = 'Notice',
    message = 'Rerunning the System Bullets AI will overwrite the previous System Bullets AI insights.',
    confirmLabel = 'Continue',
    cancelLabel = 'Cancel',
    iconVariant,
    visible = true,
    variant = 'notice',
    onConfirm,
    onCancel,
    onClose,
    onPrimary,
    onClick,
    isDisabled = false,
    isLoading = false,
    children,
    sx,
    className,
  },
  ref
) => {
  const resolvedVariant = iconVariant ?? variant;

  const handleConfirm = () => {
    onConfirm?.();
    onPrimary?.();
    onClick?.();
  };

  const handleCancel = () => {
    onCancel?.();
    onClose?.();
  };

  return (
    <MuiDialog
      ref={ref}
      open={visible}
      onClose={handleCancel}
      data-figma-component="Popup"
      className={className}
      sx={{
        '& .MuiBackdrop-root': {
          backgroundColor: 'rgba(5, 19, 33, 0.7)',
        },
        '& .MuiDialog-paper': {
          width: '277px',
          minHeight: '317px',
          backgroundColor: 'var(--color-grey-page-light, #091C2A)',
          border: '1px solid var(--color-grey-stroke, #2A4051)',
          borderRadius: '24px',
          boxShadow: '0px 8px 32px rgba(0,0,0,0.48)',
          margin: 0,
          padding: 0,
          overflow: 'visible',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
        },
        ...sx,
      }}
    >
      {/* Inner frame: Frame 2147225182 */}
      <MuiBox
        sx={{
          width: '277px',
          minHeight: '317px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 'var(--gap-space-xl, 24px)',
          padding: '24px',
          borderRadius: '24px',
          boxSizing: 'border-box',
        }}
      >
        {/* Frame 1973342171 — icon + text */}
        <MuiBox
          sx={{
            width: '229px',
            minHeight: '146px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'flex-start',
            gap: 'var(--gap-space-m, 16px)',
          }}
        >
          {/* Frame 1973342108 — icon badge */}
          <MuiBox
            sx={{
              width: '40px',
              height: '40px',
              minHeight: '40px',
              flexShrink: 0,
              borderRadius: '38px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              overflow: 'hidden',
            }}
          >
            {getIcon(resolvedVariant)}
          </MuiBox>

          {/* Frame 1973342172 — title + message */}
          <MuiBox
            sx={{
              width: '229px',
              minHeight: '90px',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'flex-start',
              gap: 'var(--gap-space-m, 16px)',
            }}
          >
            {/* Title */}
            <MuiTypography
              sx={{
                fontSize: '14px',
                fontWeight: 500,
                fontFamily: 'Inter',
                lineHeight: 'normal',
                color: 'rgba(215, 227, 236, 1)',
                textAlign: 'center',
                width: '57px',
                minHeight: '17px',
              }}
            >
              {title}
            </MuiTypography>

            {/* Body message */}
            <MuiTypography
              sx={{
                fontSize: '16px',
                fontWeight: 400,
                fontFamily: 'Inter',
                lineHeight: 'normal',
                color: 'rgba(215, 227, 236, 1)',
                textAlign: 'center',
                width: '229px',
                minHeight: '57px',
              }}
            >
              {message}
            </MuiTypography>
          </MuiBox>
        </MuiBox>

        {/* Frame 1973342158 — buttons */}
        <MuiBox
          sx={{
            width: '229px',
            minHeight: '99px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-start',
            justifyContent: 'center',
            gap: 'var(--gap-space-xs, 8px)',
          }}
        >
          {/* Primary / Continue button */}
          <MuiButton
            onClick={handleConfirm}
            disabled={isDisabled || isLoading}
            sx={{
              width: '229px',
              height: '47px',
              minHeight: '47px',
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 'var(--gap-space-10, 10px)',
              padding: '14px 10px',
              borderRadius: '12px',
              background: getButtonGradient(resolvedVariant),
              color: 'var(--color-grey-text-icons, #D7E3EC)',
              fontSize: '16px',
              fontWeight: 500,
              fontFamily: 'Inter',
              lineHeight: 'normal',
              textTransform: 'none',
              border: 'none',
              boxSizing: 'border-box',
              '&:hover': {
                opacity: 0.9,
                background: getButtonGradient(resolvedVariant),
              },
              '&:disabled': {
                opacity: 0.5,
                color: 'var(--color-grey-text-icons, #D7E3EC)',
                background: getButtonGradient(resolvedVariant),
              },
            }}
          >
            {isLoading ? 'Loading...' : confirmLabel}
          </MuiButton>

          {/* Tertiary / Cancel button */}
          <MuiButton
            onClick={handleCancel}
            disabled={isDisabled}
            sx={{
              width: '229px',
              height: '44px',
              minHeight: '44px',
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 'var(--gap-space-10, 10px)',
              padding: '12px',
              borderRadius: '58px',
              background: 'transparent',
              color: 'var(--color-purple-purple, #9B5DFF)',
              fontSize: '16px',
              fontWeight: 500,
              fontFamily: 'Inter',
              lineHeight: 'normal',
              textTransform: 'none',
              border: 'none',
              boxSizing: 'border-box',
              '&:hover': {
                background: 'rgba(155, 93, 255, 0.08)',
              },
              '&:disabled': {
                opacity: 0.5,
                color: 'var(--color-purple-purple, #9B5DFF)',
              },
            }}
          >
            {cancelLabel}
          </MuiButton>
        </MuiBox>

        {children}
      </MuiBox>
    </MuiDialog>
  );
});

Popup.displayName = 'Popup';

export { Popup };
