// @guing:generated-baseline hash:81f0c5856586
// Do not edit this file — it is used by guing for 3-way merge on re-sync
import React from 'react';
import { MuiBox, MuiTypography } from '../adapters/mui/internal';

export interface PppProps {
  label?: string;
  icon?: React.ReactNode;
  iconPosition?: 'left' | 'right';
  disabled?: boolean;
  state?: 'default' | 'pressed' | 'disabled';
  variant?: 'default' | 'pressed' | 'disabled';
  onClick?: () => void;
  onPress?: () => void;
  onRelease?: () => void;
  onHover?: () => void;
  isDisabled?: boolean;
  isLoading?: boolean;
  children?: React.ReactNode;
  sx?: Record<string, unknown>;
  className?: string;
}

const getBackgroundForState = (variant: 'default' | 'pressed' | 'disabled'): string => {
  switch (variant) {
    case 'pressed':
      return '#0a0a14';
    case 'disabled':
      return 'var(--color-neutral-300, #D1D5DB)';
    case 'default':
    default:
      return 'linear-gradient(97deg, rgba(58,62,123,1) 0%, rgba(97,74,176,1) 56.5%, rgba(155,93,255,1) 100%)';
  }
};

const getTextColorForState = (variant: 'default' | 'pressed' | 'disabled'): string => {
  switch (variant) {
    case 'disabled':
      return 'var(--color-grey-secondary-body-text, #90A3B1)';
    case 'pressed':
    case 'default':
    default:
      return 'var(--color-white-white, #FFFFFF)';
  }
};

const getShadowForState = (variant: 'default' | 'pressed' | 'disabled'): string => {
  switch (variant) {
    case 'pressed':
    case 'disabled':
      return 'none';
    case 'default':
    default:
      return '0px 1.5px 3px 0px rgba(22,5,50,0.2)';
  }
};

const Ppp = React.forwardRef<HTMLDivElement, PppProps>((
  {
    label = 'Confirm',
    icon,
    iconPosition = 'left',
    disabled = false,
    state = 'default',
    variant,
    onClick,
    onPress,
    onRelease,
    onHover,
    isDisabled = false,
    isLoading = false,
    children,
    sx,
    className,
  },
  ref
) => {
  const resolvedVariant: 'default' | 'pressed' | 'disabled' = variant ?? (
    disabled || isDisabled ? 'disabled' : state === 'pressed' ? 'pressed' : state === 'disabled' ? 'disabled' : 'default'
  );

  const isActuallyDisabled = resolvedVariant === 'disabled';
  const bg = getBackgroundForState(resolvedVariant);
  const textColor = getTextColorForState(resolvedVariant);
  const shadow = getShadowForState(resolvedVariant);

  const handleClick = () => {
    if (isActuallyDisabled) return;
    onClick?.();
  };

  const handleMouseDown = () => {
    if (isActuallyDisabled) return;
    onPress?.();
  };

  const handleMouseUp = () => {
    if (isActuallyDisabled) return;
    onRelease?.();
  };

  const handleMouseEnter = () => {
    if (isActuallyDisabled) return;
    onHover?.();
  };

  const showIcon = !!icon;
  const iconNode = showIcon ? icon : null;

  return (
    <MuiBox
      ref={ref}
      data-figma-component="Ppp"
      className={className}
      onClick={handleClick}
      onMouseDown={handleMouseDown}
      onMouseUp={handleMouseUp}
      onMouseEnter={handleMouseEnter}
      sx={{
        width: '108px',
        height: '44px',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 'var(--gap-space-xs, 8px)',
        paddingBottom: 'var(--gap-space-xs, 8px)',
        paddingLeft: 'var(--gap-space-xl, 24px)',
        paddingRight: 'var(--gap-space-xl, 24px)',
        borderRadius: '12px',
        background: bg,
        boxShadow: shadow,
        cursor: isActuallyDisabled ? 'not-allowed' : 'pointer',
        pointerEvents: isActuallyDisabled ? 'none' : 'auto',
        color: textColor,
        boxSizing: 'border-box',
        userSelect: 'none',
        transition: 'box-shadow 0.15s ease, background 0.15s ease',
        '&:hover': resolvedVariant === 'default' ? {
          boxShadow: '0px 3px 8px 0px rgba(22,5,50,0.35)',
        } : {},
        '&:active': resolvedVariant === 'default' ? {
          background: '#0a0a14',
          boxShadow: 'none',
        } : {},
        ...sx,
      }}
    >
      <MuiBox
        sx={{
          width: 'fit-content',
          height: 'fit-content',
          minHeight: 'fit-content',
          display: 'flex',
          flexDirection: iconPosition === 'right' ? 'row-reverse' : 'row',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 'var(--gap-space-xxs, 4px)',
        }}
      >
        {iconNode && (
          <MuiBox
            sx={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: textColor,
            }}
          >
            {iconNode}
          </MuiBox>
        )}
        <MuiTypography
          sx={{
            fontSize: '14px',
            fontWeight: 500,
            fontFamily: 'Inter, sans-serif',
            lineHeight: 'normal',
            color: textColor,
            whiteSpace: 'nowrap',
          }}
        >
          {children ?? label}
        </MuiTypography>
      </MuiBox>
    </MuiBox>
  );
});

Ppp.displayName = 'Ppp';

export { Ppp };
