// @guing:generated-baseline hash:d30882876e05
// Do not edit this file — it is used by guing for 3-way merge on re-sync
// src/components/Search/Search.tsx
import React from 'react';
import { MuiBox, MuiInputBase } from '../adapters/mui/internal';

const SEARCH_ICON_SVG = `<svg width="64" height="20" viewBox="0 0 64 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.5 17.5L13.8834 13.8834" stroke="white" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.16667 15.8333C12.8486 15.8333 15.8333 12.8486 15.8333 9.16667C15.8333 5.48477 12.8486 2.5 9.16667 2.5C5.48477 2.5 2.5 5.48477 2.5 9.16667C2.5 12.8486 5.48477 15.8333 9.16667 15.8333Z" stroke="white" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/><line x1="32.5" y1="3" x2="32.5" y2="17" stroke="#90A3B1"/><path d="M49 7.5L54 12.5L59 7.5" stroke="white" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

export interface SearchProps {
  showAiSearch?: boolean;
  showSearchIcon?: boolean;
  showArrowIcon?: boolean;
  arrowBackIcon?: boolean;
  onClick?: () => void;
  onHover?: () => void;
  isDisabled?: boolean;
  isLoading?: boolean;
  children?: React.ReactNode;
  sx?: Record<string, unknown>;
  className?: string;
}

const Search = React.forwardRef<HTMLDivElement, SearchProps>(({
  showAiSearch = false,
  showSearchIcon = true,
  showArrowIcon = false,
  arrowBackIcon = false,
  onClick,
  onHover,
  isDisabled = false,
  isLoading = false,
  children,
  sx = {},
  className,
}, ref) => {
  return (
    <MuiBox
      ref={ref}
      onClick={onClick}
      onMouseEnter={onHover}
      className={className}
      sx={{
        display: 'flex',
        alignItems: 'center',
        backgroundColor: 'var(--color-grey-text-field, #2F3649)',
        color: 'var(--color-grey-secondary-body-text, #90A3B1)',
        border: '1px solid var(--color-grey-stroke, #2A4051)',
        borderRadius: 'var(--radius-radius-xxs, 2px)',
        padding: '12px 16px',
        gap: 'var(--gap-16, 16px)',
        fontSize: 'var(--font-headline-med-headline-reg-label-large-14-med-size, 14px)',
        fontFamily: 'var(--font-headline-med-headline-reg-label-large-14-med-family, Inter)',
        fontWeight: 'var(--font-headline-med-headline-reg-label-large-14-med-weight, 500)',
        width: '343px',
        height: '44px',
        '&:disabled, &[aria-disabled="true"]': {
          opacity: '0.5',
        },
        ...sx,
      }}
      aria-disabled={isDisabled || isLoading}
    >
      {showSearchIcon && (
        <span aria-hidden style={{ display: 'inline-flex' }} dangerouslySetInnerHTML={{ __html: SEARCH_ICON_SVG }} />
      )}
      <MuiInputBase
        placeholder="Search..."
        disabled={isDisabled || isLoading}
        sx={{
          flex: 1,
          color: 'inherit',
          '&::placeholder': {
            color: 'inherit',
            opacity: 1,
          },
        }}
      />
      {showArrowIcon && (
        <span aria-hidden style={{ display: 'inline-flex' }} dangerouslySetInnerHTML={{ __html: SEARCH_ICON_SVG }} />
      )}
    </MuiBox>
  );
});

export { Search };