// @guing:generated-baseline hash:059bf593784f
// Do not edit this file — it is used by guing for 3-way merge on re-sync
import React, { forwardRef } from 'react';
import { MuiBox, MuiInputBase } from '../adapters/mui/internal';

export interface SearchProps {
  variant?: 'searchBar' | 'searchAI';
  placeholder?: string;
  value?: string;
  showDropdown?: boolean;
  showDivider?: boolean;
  icon?: React.ReactNode;
  disabled?: boolean;
  onChange?: (value: string) => void;
  onSearch?: () => void;
  onDropdownToggle?: () => void;
  onFocus?: () => void;
  onBlur?: () => void;
  showAisearch5420?: boolean;
  showSearchIcon5423?: boolean;
  showArrowIcon5426?: boolean;
  arrowBackIcon5790?: boolean;
  property1?: 'Search Bar - Back' | 'Search AI';
  onCancel?: () => void;
  onClick?: () => void;
  onHover?: () => void;
  isDisabled?: boolean;
  isLoading?: boolean;
  children?: React.ReactNode;
  sx?: Record<string, unknown>;
  className?: string;
}

const SearchBarIconSVG = () => (
  <svg width="64" height="20" viewBox="0 0 64 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M17.5 17.5L13.8834 13.8834" stroke="#D7E3EC" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M9.16667 15.8333C12.8486 15.8333 15.8333 12.8486 15.8333 9.16667C15.8333 5.48477 12.8486 2.5 9.16667 2.5C5.48477 2.5 2.5 5.48477 2.5 9.16667C2.5 12.8486 5.48477 15.8333 9.16667 15.8333Z" stroke="#D7E3EC" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
    <line x1="32.5" y1="3" x2="32.5" y2="17" stroke="#90A3B1"/>
    <path d="M49 7.5L54 12.5L59 7.5" stroke="#D7E3EC" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"/>
  </svg>
);

const AISearchIconSVG = () => (
  <svg width="64" height="20" viewBox="0 0 64 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M9.16667 5C7.51184 5 5.92591 5.65848 4.75068 6.83371C3.57545 8.00895 2.91667 9.59489 2.91667 11.25C2.91667 12.9051 3.57545 14.4911 4.75068 15.6663C5.92591 16.8415 7.51184 17.5 9.16667 17.5C10.8215 17.5 12.4074 16.8415 13.5827 15.6663C14.7579 14.4911 15.4167 12.9051 15.4167 11.25" stroke="#D7E3EC" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M9.16667 2.5V5" stroke="#D7E3EC" strokeWidth="1.25" strokeLinecap="round"/>
    <path d="M13.8834 3.88672L12.2167 5.55339" stroke="#9B5DFF" strokeWidth="1.25" strokeLinecap="round"/>
    <path d="M15.8333 8.33398H13.5" stroke="#9B5DFF" strokeWidth="1.25" strokeLinecap="round"/>
    <line x1="32.5" y1="3" x2="32.5" y2="17" stroke="#90A3B1"/>
    <path d="M49 7.5L54 12.5L59 7.5" stroke="#D7E3EC" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"/>
  </svg>
);

const Search = forwardRef<HTMLDivElement, SearchProps>((
  {
    variant = 'searchBar',
    placeholder,
    value,
    showDropdown = true,
    showDivider = true,
    icon,
    disabled = false,
    onChange,
    onSearch,
    onDropdownToggle,
    onFocus,
    onBlur,
    showAisearch5420 = true,
    showSearchIcon5423 = true,
    showArrowIcon5426 = true,
    arrowBackIcon5790 = false,
    property1 = 'Search Bar - Back',
    onCancel,
    onClick,
    onHover,
    isDisabled = false,
    isLoading = false,
    children,
    sx,
    className,
  },
  ref
) => {
  const isAI = variant === 'searchAI' || property1 === 'Search AI';
  const isComponentDisabled = disabled || isDisabled;

  const derivedPlaceholder = placeholder ?? (isAI ? 'Search Meetings...' : 'Search...');

  const borderStyle = isAI
    ? '1px solid var(--color-purple-purple, #9B5DFF)'
    : '1px solid var(--color-grey-stroke, #2A4051)';

  const boxShadow = isAI
    ? '0 0 0 2px rgba(155, 93, 255, 0.25)'
    : 'none';

  return (
    <MuiBox
      ref={ref}
      data-figma-component="Search"
      className={className}
      onClick={onClick}
      onMouseEnter={onHover}
      sx={{
        width: '343px',
        minHeight: '44px',
        height: '44px',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        color: 'var(--color-grey-secondary-body-text, #90A3B1)',
        opacity: isComponentDisabled ? 0.5 : 1,
        pointerEvents: isComponentDisabled ? 'none' : 'auto',
        ...sx,
      }}
    >
      {/* Frame 1410103816 */}
      <MuiBox
        sx={{
          width: '343px',
          height: '44px',
          minHeight: '44px',
          display: 'flex',
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
          paddingLeft: '16px',
          paddingRight: '16px',
          borderRadius: 'var(--radius-radius-full, 99px)',
          backgroundColor: 'var(--color-grey-text-field, #2F3649)',
          border: borderStyle,
          boxShadow: boxShadow,
          boxSizing: 'border-box',
        }}
      >
        {/* Frame 2147225554 — left: placeholder/input text, 59×17px */}
        <MuiBox
          sx={{
            width: '59px',
            minHeight: '17px',
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            flex: 1,
            overflow: 'hidden',
          }}
        >
          <MuiInputBase
            value={value}
            onChange={(e) => onChange?.(e.target.value)}
            onFocus={onFocus}
            onBlur={onBlur}
            disabled={isComponentDisabled}
            onKeyDown={(e) => { if (e.key === 'Enter') onSearch?.(); }}
            placeholder={derivedPlaceholder}
            sx={{
              fontSize: 'var(--font-label-reg-14-reg-size, 14px)',
              fontWeight: 'var(--font-label-reg-14-reg-weight, 400)',
              fontFamily: 'var(--font-label-reg-14-reg-family, Inter)',
              lineHeight: 'normal',
              color: 'var(--color-grey-secondary-body-text, #90A3B1)',
              width: '100%',
              '& input': {
                fontSize: 'var(--font-label-reg-14-reg-size, 14px)',
                fontWeight: 'var(--font-label-reg-14-reg-weight, 400)',
                fontFamily: 'var(--font-label-reg-14-reg-family, Inter)',
                lineHeight: 'normal',
                color: 'var(--color-grey-secondary-body-text, #90A3B1)',
                padding: 0,
                '&::placeholder': {
                  color: 'var(--color-grey-secondary-body-text, #90A3B1)',
                  opacity: 1,
                },
              },
            }}
          />
        </MuiBox>

        {/* Frame 2147225553 — right: search icon + divider + chevron, 64×20px */}
        <MuiBox
          sx={{
            width: '64px',
            height: '20px',
            minHeight: '20px',
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            flexShrink: 0,
            cursor: 'pointer',
          }}
          onClick={(e) => {
            e.stopPropagation();
            onDropdownToggle?.();
          }}
        >
          {icon ? icon : (isAI ? <AISearchIconSVG /> : <SearchBarIconSVG />)}
        </MuiBox>
      </MuiBox>
      {children}
    </MuiBox>
  );
});

Search.displayName = 'Search';

export { Search };
