/* Auto-generated by Guing — do not edit manually */

// Design Tokens
export * from './design-tokens';
export * from './design-tokens/vars';

// Token-driven typography bridge — every Figma typography token becomes <Typography.XxxYyy>
export { Typography } from './components/Text/Text';

// Figma-mapped components (override library defaults for same-named exports)
export { TasksContentPage } from './components/TasksContentPage';
